/**
 * Усі тексти застосунку — в одному місці.
 *
 * Ключ -> чотири мови. Раніше словники жили в i18n.js, а тексти екскурсії,
 * розповіді про Шелдона й фактів — просто рядками в коді, тому половина з
 * них існувала лише українською. Тепер будь-який текст видно поруч із
 * перекладами, і пропущений одразу помітно.
 *
 * Плейсхолдери у фігурних дужках підставляє t() з i18n.js.
 */

export const LANGUAGES = ['en', 'de', 'pl', 'uk'];

export const STRINGS = {
  'app.title': {
    uk: 'Куди доїду за день',
    en: 'Where can I get in a day',
    de: 'Wohin komme ich an einem Tag',
    pl: 'Dokąd dojadę w jeden dzień',
  },
  'window.legend': {
    uk: 'Вікно поїздки',
    en: 'Trip window',
    de: 'Zeitfenster',
    pl: 'Okno wyjazdu',
  },
  'window.day': {
    uk: 'День',
    en: 'Day',
    de: 'Tag',
    pl: 'Dzień',
  },
  'window.day.range': {
    uk: 'пн 09:00 → 23:00',
    en: 'Mon 09:00 → 23:00',
    de: 'Mo 09:00 → 23:00',
    pl: 'pon 09:00 → 23:00',
  },
  'window.night': {
    uk: 'Доба',
    en: 'Overnight',
    de: 'Über Nacht',
    pl: 'Doba',
  },
  'window.night.range': {
    uk: 'пн 09:00 → вт 09:00',
    en: 'Mon 09:00 → Tue 09:00',
    de: 'Mo 09:00 → Di 09:00',
    pl: 'pon 09:00 → wt 09:00',
  },
  'field.from': {
    uk: 'Звідки',
    en: 'From',
    de: 'Von',
    pl: 'Skąd',
  },
  'field.pick': {
    uk: '— оберіть станцію —',
    en: '— pick a station —',
    de: '— Station wählen —',
    pl: '— wybierz stację —',
  },
  'field.minStay': {
    uk: 'Мінімум на місці',
    en: 'Minimum on site',
    de: 'Mindestens vor Ort',
    pl: 'Minimum na miejscu',
  },
  'field.overhead': {
    uk: 'Кава й хотдог',
    en: 'Coffee and a hotdog',
    de: 'Kaffee und Hotdog',
    pl: 'Kawa i hot dog',
  },
  'field.zones': {
    uk: 'Показувати зони',
    en: 'Show zones',
    de: 'Zonen anzeigen',
    pl: 'Pokaż strefy',
  },
  'legend.title': {
    uk: 'Корисних годин на місці',
    en: 'Useful hours on site',
    de: 'Nutzbare Stunden vor Ort',
    pl: 'Użytecznych godzin na miejscu',
  },
  'legend.under': {
    uk: 'до {h}',
    en: 'under {h}',
    de: 'unter {h}',
    pl: 'poniżej {h}',
  },
  'legend.between': {
    uk: '{a} — {b}',
    en: '{a} — {b}',
    de: '{a} — {b}',
    pl: '{a} — {b}',
  },
  'legend.orMore': {
    uk: '{h} і більше',
    en: '{h} or more',
    de: '{h} und mehr',
    pl: '{h} i więcej',
  },
  'status.loading': {
    uk: 'Завантажую розклад…',
    en: 'Loading the timetable…',
    de: 'Fahrplan wird geladen…',
    pl: 'Wczytuję rozkład…',
  },
  'status.pick': {
    uk: 'Клікніть по карті — візьму найближчу станцію.',
    en: 'Click the map — I’ll take the nearest station.',
    de: 'Auf die Karte klicken — ich nehme die nächste Station.',
    pl: 'Kliknij na mapie — wezmę najbliższą stację.',
  },
  'status.computing': {
    uk: 'Рахую…',
    en: 'Computing…',
    de: 'Wird berechnet…',
    pl: 'Liczę…',
  },
  'status.result': {
    uk: '<strong>{n}</strong> станцій з <em>{name}</em>',
    en: '<strong>{n}</strong> stations from <em>{name}</em>',
    de: '<strong>{n}</strong> Stationen ab <em>{name}</em>',
    pl: '<strong>{n}</strong> stacji z <em>{name}</em>',
  },
  'status.empty': {
    uk: 'З <em>{name}</em> за цей день нікуди не зʼїздиш',
    en: 'Nowhere to go from <em>{name}</em> on this day',
    de: 'Von <em>{name}</em> kommt man an diesem Tag nirgendwohin',
    pl: 'Z <em>{name}</em> nie da się nigdzie pojechać tego dnia',
  },
  'status.retry': {
    uk: 'Спробувати ще',
    en: 'Try again',
    de: 'Erneut versuchen',
    pl: 'Spróbuj ponownie',
  },
  'error.stations': {
    uk: 'Не вдалося завантажити список станцій ({message}).',
    en: 'Could not load the station list ({message}).',
    de: 'Die Stationsliste konnte nicht geladen werden ({message}).',
    pl: 'Nie udało się wczytać listy stacji ({message}).',
  },
  'error.routes': {
    uk: 'Не вдалося порахувати маршрути ({message}).',
    en: 'Could not compute the routes ({message}).',
    de: 'Die Verbindungen konnten nicht berechnet werden ({message}).',
    pl: 'Nie udało się policzyć połączeń ({message}).',
  },
  // Заголовок нейтральний: розклад понеділковий, а дивляться на нього
  // будь-якого дня тижня — «Понеділок у русі» в середу виглядало дивно.
  'screen.title': {
    uk: 'Країна в русі',
    en: 'A country in motion',
    de: 'Ein Land in Bewegung',
    pl: 'Kraj w ruchu',
  },
  'screen.lead': {
    uk: 'Підсвічені станції — ті, де просто зараз стоїть потяг.',
    en: 'Highlighted stations are the ones where a train is standing right now.',
    de: 'Hervorgehoben sind die Stationen, an denen gerade ein Zug steht.',
    pl: 'Podświetlone stacje to te, na których właśnie stoi pociąg.',
  },
  'screen.pulse': {
    uk: 'Пульс дня',
    en: 'Pulse of the day',
    de: 'Puls des Tages',
    pl: 'Puls dnia',
  },
  'screen.today': {
    uk: 'Сьогодні від півночі',
    en: 'Since midnight',
    de: 'Seit Mitternacht',
    pl: 'Od północy',
  },
  'screen.km': {
    uk: 'поїздо-кілометрів',
    en: 'train-kilometres',
    de: 'Zugkilometer',
    pl: 'pociągokilometry',
  },
  'screen.rate': {
    uk: 'відправлень щохвилини',
    en: 'departures per minute',
    de: 'Abfahrten pro Minute',
    pl: 'odjazdów na minutę',
  },
  'screen.peak': {
    uk: 'Найгустіше о {time} — {n} потягів на зупинках',
    en: 'Busiest at {time} — {n} trains at platforms',
    de: 'Am dichtesten um {time} — {n} Züge an den Bahnsteigen',
    pl: 'Najgęściej o {time} — {n} pociągów na peronach',
  },
  'screen.seconds': {
    uk: '{n} с',
    en: '{n} s',
    de: '{n} s',
    pl: '{n} s',
  },
  'screen.hideSettings': {
    uk: 'Сховати налаштування',
    en: 'Hide settings',
    de: 'Einstellungen ausblenden',
    pl: 'Ukryj ustawienia',
  },
  'screen.showSettings': {
    uk: 'Налаштування',
    en: 'Settings',
    de: 'Einstellungen',
    pl: 'Ustawienia',
  },
  'screen.hidePanel': {
    uk: 'Сховати панель',
    en: 'Hide panel',
    de: 'Panel ausblenden',
    pl: 'Ukryj panel',
  },
  'screen.showPanel': {
    uk: 'Показати панель',
    en: 'Show panel',
    de: 'Panel einblenden',
    pl: 'Pokaż panel',
  },
  'screen.scopeGroup': {
    uk: 'Звідки брати потяги',
    en: 'Where to take trains from',
    de: 'Woher die Züge kommen',
    pl: 'Skąd brać pociągi',
  },
  'screen.scopeAll': {
    uk: 'Уся карта',
    en: 'Whole map',
    de: 'Ganze Karte',
    pl: 'Cała mapa',
  },
  'screen.scopeView': {
    uk: 'Видима частина',
    en: 'Visible part',
    de: 'Sichtbarer Teil',
    pl: 'Widoczna część',
  },
  'screen.standing': {
    uk: 'стоять',
    en: 'standing',
    de: 'stehen',
    pl: 'stoją',
  },
  'screen.leaving': {
    uk: 'рушають за 30 с',
    en: 'leaving in 30 s',
    de: 'fahren in 30 s',
    pl: 'ruszają za 30 s',
  },
  'screen.left': {
    uk: 'щойно приїхали',
    en: 'just arrived',
    de: 'gerade angekommen',
    pl: 'właśnie przyjechały',
  },
  'screen.departures': {
    uk: 'Ось-ось відправляться',
    en: 'About to depart',
    de: 'Fahren gleich ab',
    pl: 'Zaraz odjadą',
  },
  // Табло потяга: підпис ліворуч, значення у фіксованих слотах. Підписи
  // коротші за 13 символів — саме стільки має колонка.
  // Назва лінії, коли в даних її немає: у фіді трапляються рейси без номера.
  'screen.now': { uk: 'потяг', en: 'train', de: 'Zug', pl: 'pociąg' },
  'screen.pause': {
    uk: 'Пауза між показами',
    en: 'Pause between shows',
    de: 'Pause dazwischen',
    pl: 'Przerwa między pokazami',
  },
  'screen.refresh': {
    uk: 'Оновлення віджета',
    en: 'Widget refresh',
    de: 'Widget-Wechsel',
    pl: 'Odświeżanie widżetu',
  },
  'screen.region': {
    uk: 'Моя область',
    en: 'My region',
    de: 'Mein Bundesland',
    pl: 'Mój region',
  },
  'screen.regionAll': {
    uk: '— уся Німеччина —',
    en: '— all of Germany —',
    de: '— ganz Deutschland —',
    pl: '— całe Niemcy —',
  },
  'screen.states': {
    uk: 'Де зараз рух',
    en: 'Where the movement is',
    de: 'Wo gerade Bewegung ist',
    pl: 'Gdzie teraz ruch',
  },
  'screen.kinds': {
    uk: 'Хто зараз їде',
    en: 'What is running',
    de: 'Was gerade fährt',
    pl: 'Co teraz jedzie',
  },
  'screen.kind.S': { uk: 'S-Bahn', en: 'S-Bahn', de: 'S-Bahn', pl: 'S-Bahn' },
  'screen.kind.RE': { uk: 'RE', en: 'RE', de: 'RE', pl: 'RE' },
  'screen.kind.RB': { uk: 'RB', en: 'RB', de: 'RB', pl: 'RB' },
  'screen.kind.other': { uk: 'інші', en: 'other', de: 'andere', pl: 'inne' },
  'screen.edges': {
    uk: 'Крайні точки',
    en: 'Far ends',
    de: 'Äußerste Punkte',
    pl: 'Skrajne punkty',
  },
  'screen.north': { uk: 'найпівнічніший', en: 'northernmost', de: 'nördlichster', pl: 'najdalej na północ' },
  'screen.south': { uk: 'найпівденніший', en: 'southernmost', de: 'südlichster', pl: 'najdalej na południe' },
  'board.line': { uk: 'лінія', en: 'line', de: 'Linie', pl: 'linia' },
  'board.from': { uk: 'потяг з', en: 'train from', de: 'Zug ab', pl: 'pociąg z' },
  'board.to': { uk: 'прямує до', en: 'heading to', de: 'Ziel', pl: 'do' },
  'board.departs': { uk: 'відправлення', en: 'departure', de: 'Abfahrt', pl: 'odjazd' },
  'board.departsValue': {
    uk: 'за {min} хв · колія {track}',
    en: 'in {min} min · track {track}',
    de: 'in {min} Min · Gleis {track}',
    pl: 'za {min} min · tor {track}',
  },
  'board.stop': { uk: 'зупинка', en: 'stop', de: 'Halt', pl: 'przystanek' },
  'board.stopValue': {
    uk: '{n} з {total} · {time}',
    en: '{n} of {total} · {time}',
    de: '{n} von {total} · {time}',
    pl: '{n} z {total} · {time}',
  },
  'screen.settings': {
    uk: 'Плин часу',
    en: 'Flow of time',
    de: 'Lauf der Zeit',
    pl: 'Bieg czasu',
  },
  'screen.real': {
    uk: 'Реальний час',
    en: 'Real time',
    de: 'Echtzeit',
    pl: 'Czas rzeczywisty',
  },
  'screen.fast': {
    uk: 'Прискорено',
    en: 'Accelerated',
    de: 'Im Zeitraffer',
    pl: 'Przyspieszony',
  },
  'screen.duration': {
    uk: 'Весь день за',
    en: 'Whole day in',
    de: 'Ganzer Tag in',
    pl: 'Cały dzień w',
  },
  'screen.minutes': {
    uk: '{n} хв',
    en: '{n} min',
    de: '{n} Min',
    pl: '{n} min',
  },
  'map.group': {
    uk: 'Підкладка',
    en: 'Base map',
    de: 'Grundkarte',
    pl: 'Podkład',
  },
  'map.own': {
    uk: 'Своя',
    en: 'Ours',
    de: 'Eigene',
    pl: 'Własna',
  },
  'map.osm': {
    uk: 'OSM',
    en: 'OSM',
    de: 'OSM',
    pl: 'OSM',
  },
  'mode.group': {
    uk: 'Режим карти',
    en: 'Map mode',
    de: 'Kartenmodus',
    pl: 'Tryb mapy',
  },
  'intro.p4': {
    uk: 'Клікніть на карті там, де ви зараз. Ця карта рахує не час у дорозі, а час на місці: скільки годин лишається вам, якщо ввечері треба повернутись додому.',
    en: 'Click on the map where you are now. This map counts not the time in transit but the time on the ground: how many hours are left to you if you have to be home in the evening.',
    de: 'Klicken Sie auf der Karte dorthin, wo Sie gerade sind. Diese Karte zählt nicht die Fahrzeit, sondern die Zeit vor Ort: wie viele Stunden Ihnen bleiben, wenn Sie abends zu Hause sein müssen.',
    pl: 'Kliknij na mapie tam, gdzie jesteś teraz. Ta mapa liczy nie czas w drodze, lecz czas na miejscu: ile godzin ci zostanie, jeśli wieczorem trzeba wrócić do domu.',
  },
  'screen.tabBoards': {
    uk: 'Дашборди',
    en: 'Dashboards',
    de: 'Dashboards',
    pl: 'Pulpity',
  },
  'screen.tabSettings': {
    uk: 'Налаштування',
    en: 'Settings',
    de: 'Einstellungen',
    pl: 'Ustawienia',
  },
  'screen.board': {
    uk: 'Зміна на табло',
    en: 'Board changes every',
    de: 'Anzeige wechselt alle',
    pl: 'Zmiana tablicy co',
  },
  'screen.fact': {
    uk: 'Факт тримається',
    en: 'Fact stays for',
    de: 'Fakt bleibt',
    pl: 'Fakt trwa',
  },
  'about.how': {
    uk: 'Нічого не пораховано наперед. Браузер один раз завантажує компактний бінарний розклад і рахує маршрути сам, у фоновому потоці, — тому стартом може бути будь-яка з 7737 станцій, куди ви клікнете.',
    en: 'Nothing is precomputed. The browser loads a compact binary timetable once and works the routes out itself, in a background thread — so the origin can be any of the 7737 stations you click on.',
    de: 'Nichts ist vorberechnet. Der Browser lädt einmal einen kompakten binären Fahrplan und rechnet die Verbindungen selbst, in einem Hintergrund-Thread — der Start kann also jede der 7737 Stationen sein, die Sie anklicken.',
    pl: 'Nic nie jest policzone z góry. Przeglądarka raz wczytuje kompaktowy binarny rozkład i sama liczy trasy, w wątku w tle — więc początkiem może być każda z 7737 stacji, którą klikniesz.',
  },
  'about.qr': {
    uk: 'Якщо карта стала в пригоді — можна поставити мені каву. Код і дані від цього не зміняться: усе лишиться відкритим.',
    en: 'If the map came in useful, you can buy me a coffee. It changes nothing about the code or the data: both stay open.',
    de: 'Wenn die Karte nützlich war, können Sie mir einen Kaffee ausgeben. Am Code und an den Daten ändert das nichts: beides bleibt offen.',
    pl: 'Jeśli mapa się przydała, możesz postawić mi kawę. Nic to nie zmienia w kodzie ani w danych: jedno i drugie zostaje otwarte.',
  },
  'about.qrAlt': {
    uk: 'QR-код на сторінку підтримки',
    en: 'A QR code to the support page',
    de: 'Ein QR-Code zur Unterstützungsseite',
    pl: 'Kod QR do strony wsparcia',
  },
  'about.code': {
    uk: 'Код на GitHub',
    en: 'Code on GitHub',
    de: 'Code auf GitHub',
    pl: 'Kod na GitHubie',
  },
  'about.sources': {
    uk: 'Джерела даних',
    en: 'Data sources',
    de: 'Datenquellen',
    pl: 'Źródła danych',
  },
  'about.coffee': {
    uk: 'Купити мені каву',
    en: 'Buy me a coffee',
    de: 'Kauf mir einen Kaffee',
    pl: 'Postaw mi kawę',
  },
  'intro.pick': {
    uk: 'З чого почнемо?',
    en: 'Where shall we start?',
    de: 'Womit fangen wir an?',
    pl: 'Od czego zaczniemy?',
  },
  'intro.day': {
    uk: 'карта одноденних поїздок',
    en: 'map of one-day trips',
    de: 'Karte der Tagesausflüge',
    pl: 'mapa jednodniowych wypraw',
  },
  'intro.sheldon': {
    uk: 'історія однієї поїздки',
    en: 'the story of one trip',
    de: 'die Geschichte einer Reise',
    pl: 'historia jednej podróży',
  },
  'intro.screen': {
    uk: 'розклад у русі, без кліків',
    en: 'the timetable in motion, no clicks',
    de: 'der Fahrplan in Bewegung, ohne Klicks',
    pl: 'rozkład w ruchu, bez klikania',
  },
  'intro.tour': {
    uk: 'Показати екскурсію',
    en: 'Take the tour',
    de: 'Rundgang starten',
    pl: 'Pokaż wycieczkę',
  },
  'tour.prev': {
    uk: 'Назад',
    en: 'Back',
    de: 'Zurück',
    pl: 'Wstecz',
  },
  'tour.next': {
    uk: 'Далі',
    en: 'Next',
    de: 'Weiter',
    pl: 'Dalej',
  },
  'tour.done': {
    uk: 'Готово',
    en: 'Done',
    de: 'Fertig',
    pl: 'Gotowe',
  },
  'tour.skip': {
    uk: 'Пропустити',
    en: 'Skip',
    de: 'Überspringen',
    pl: 'Pomiń',
  },
  'tour.step': {
    uk: 'крок {n} з {total}',
    en: 'step {n} of {total}',
    de: 'Schritt {n} von {total}',
    pl: 'krok {n} z {total}',
  },
  'mode.day': {
    uk: 'Куди доїду',
    en: 'Where can I get',
    de: 'Wohin komme ich',
    pl: 'Dokąd dojadę',
  },
  'mode.sheldon': {
    uk: 'Маршрут Шелдона',
    en: 'Sheldon’s route',
    de: 'Sheldons Route',
    pl: 'Trasa Sheldona',
  },
  'mode.screen': {
    uk: 'Скрінсейвер',
    en: 'Screensaver',
    de: 'Bildschirmschoner',
    pl: 'Wygaszacz',
  },
  'theme.group': {
    uk: 'Тема',
    en: 'Theme',
    de: 'Erscheinungsbild',
    pl: 'Motyw',
  },
  'theme.light': {
    uk: 'Світла тема',
    en: 'Light theme',
    de: 'Helles Design',
    pl: 'Jasny motyw',
  },
  'theme.dark': {
    uk: 'Темна тема',
    en: 'Dark theme',
    de: 'Dunkles Design',
    pl: 'Ciemny motyw',
  },
  'hint.useful': {
    uk: '{h} год {m} хв на місці',
    en: '{h} h {m} min on site',
    de: '{h} Std {m} Min vor Ort',
    pl: '{h} godz {m} min na miejscu',
  },
  'hint.times': {
    uk: 'приїзд {a} · назад {d}',
    en: 'arrive {a} · back {d}',
    de: 'an {a} · zurück {d}',
    pl: 'przyjazd {a} · powrót {d}',
  },
  'intro.open': {
    uk: 'Навіщо це',
    en: 'Why this exists',
    de: 'Wozu das alles',
    pl: 'Po co to',
  },
  'intro.title': {
    uk: 'Понеділок можна не працювати',
    en: 'You don’t have to work on Monday',
    de: 'Montag muss kein Arbeitstag sein',
    pl: 'W poniedziałek nie musisz pracować',
  },
  'intro.p1': {
    uk: 'Код тепер зʼявляється швидше, ніж ми встигаємо його читати. Модель пише за хвилину те, на що раніше йшов день, — і цей день нікуди не зник: він просто заповнився наступними задачами.',
    en: 'Code now appears faster than we can read it. A model writes in a minute what used to take a day — and that day has not gone anywhere: it simply filled up with the next tasks.',
    de: 'Code entsteht heute schneller, als wir ihn lesen können. Ein Modell schreibt in einer Minute, wofür früher ein Tag nötig war — und dieser Tag ist nicht verschwunden: er hat sich mit den nächsten Aufgaben gefüllt.',
    pl: 'Kod powstaje teraz szybciej, niż zdążymy go przeczytać. Model pisze w minutę to, co kiedyś zajmowało dzień — a ten dzień nie zniknął: po prostu wypełnił się kolejnymi zadaniami.',
  },
  'intro.p2': {
    uk: 'Ревʼю не наздоганяє генерацію, спринт стискається, реліз їде щодня. Зникає пауза, у якій колись відбувалось найважливіше — думання. Вигоряння перестає бути метафорою: воно просто стоїть у календарі, між дейлі й демо.',
    en: 'Review never catches up with generation, the sprint contracts, a release goes out every day. What disappears is the pause where the most important thing used to happen — thinking. Burnout stops being a metaphor: it simply sits in the calendar, between the standup and the demo.',
    de: 'Das Review holt die Generierung nicht ein, der Sprint schrumpft, das Release geht täglich raus. Verloren geht die Pause, in der früher das Wichtigste passierte — das Nachdenken. Burnout ist keine Metapher mehr: es steht schlicht im Kalender, zwischen Daily und Demo.',
    pl: 'Przegląd nie nadąża za generowaniem, sprint się kurczy, wydanie wychodzi codziennie. Znika pauza, w której kiedyś działo się najważniejsze — myślenie. Wypalenie przestaje być metaforą: po prostu stoi w kalendarzu, między dailym a demo.',
  },
  'intro.p3': {
    uk: 'Якщо ви впізнали себе — зробіть як Шелдон Купер: у понеділок замість роботи сядьте в поїзд і їдьте в інше місто. Прогулянка, чужий вокзал, кава з хотдогом, блокнот біля вікна.',
    en: 'If that sounds familiar, do what Sheldon Cooper did: on a Monday, instead of working, get on a train and go to another city. A walk, someone else’s station, a coffee with a hotdog, a notebook by the window.',
    de: 'Wenn Sie sich wiedererkennen, machen Sie es wie Sheldon Cooper: steigen Sie am Montag statt zu arbeiten in einen Zug und fahren Sie in eine andere Stadt. Ein Spaziergang, ein fremder Bahnhof, ein Kaffee mit Hotdog, ein Notizbuch am Fenster.',
    pl: 'Jeśli to brzmi znajomo, zrób jak Sheldon Cooper: w poniedziałek zamiast pracy wsiądź do pociągu i jedź do innego miasta. Spacer, cudzy dworzec, kawa z hotdogiem, notes przy oknie.',
  },
  'photo.alt': {
    uk: 'Купе поїзда: пасажир із блокнотом біля вікна, за вікном перонний візок',
    en: 'A train compartment: a passenger with a notebook by the window, a platform cart outside',
    de: 'Ein Zugabteil: ein Fahrgast mit Notizbuch am Fenster, draußen ein Bahnsteigwagen',
    pl: 'Przedział pociągu: pasażer z notesem przy oknie, za oknem wózek na peronie',
  },
  'timeline.play': {
    uk: 'Програти день',
    en: 'Play the day',
    de: 'Tag abspielen',
    pl: 'Odtwórz dzień',
  },
  'timeline.pause': {
    uk: 'Пауза',
    en: 'Pause',
    de: 'Pause',
    pl: 'Pauza',
  },
  'timeline.live': {
    uk: '{n} досяжних',
    en: '{n} reachable',
    de: '{n} erreichbar',
    pl: '{n} osiągalnych',
  },
  'time.nextDay': {
    uk: 'вт',
    en: 'Tue',
    de: 'Di',
    pl: 'wt',
  },
  'time.hours': {
    uk: '{h} год',
    en: '{h} h',
    de: '{h} Std',
    pl: '{h} godz',
  },
  'time.hoursMinutes': {
    uk: '{h} год {m} хв',
    en: '{h} h {m} min',
    de: '{h} Std {m} Min',
    pl: '{h} godz {m} min',
  },

  // --- екскурсія ---
  'tour.params.title': {
    uk: 'Час на місці, а не в дорозі',
    en: 'Time on site, not time in transit',
    de: 'Zeit vor Ort, nicht Zeit im Zug',
    pl: 'Czas na miejscu, a nie w drodze',
  },
  'tour.params.text': {
    uk: 'Гамбург за дві години в дорозі марний, якщо назад є один вечірній потяг. Ці два повзунки задають, скільки корисного часу вам треба на місці й скільки з нього піде на вокзал, каву й хотдог.',
    en: 'Hamburg two hours away is useless if there is a single evening train back. These two sliders set how much useful time you need on site and how much of it goes to the station, coffee and a hotdog.',
    de: 'Hamburg in zwei Stunden nützt nichts, wenn zurück nur ein Abendzug fährt. Diese zwei Regler bestimmen, wie viel nutzbare Zeit Sie vor Ort brauchen und wie viel davon für Bahnhof, Kaffee und Hotdog draufgeht.',
    pl: 'Hamburg o dwie godziny drogi jest bezużyteczny, jeśli z powrotem jedzie jeden wieczorny pociąg. Te dwa suwaki ustalają, ile użytecznego czasu potrzebujesz na miejscu i ile z niego pochłonie dworzec, kawa i hot dog.',
  },
  'tour.map.title': {
    uk: 'Клікніть будь-де',
    en: 'Click anywhere',
    de: 'Klicken Sie irgendwohin',
    pl: 'Kliknij gdziekolwiek',
  },
  'tour.map.text': {
    uk: 'Стартом може бути будь-яка з 6 761 станції — я беру найближчу до кліку. Колір крапки каже, скільки годин там лишається, якщо встигнути повернутись.',
    en: 'Any of the 6,761 stations can be the start — I take the one nearest your click. The colour of a dot says how many hours you get there if you still make it back.',
    de: 'Jede der 6 761 Stationen kann der Start sein — ich nehme die dem Klick nächste. Die Farbe eines Punktes zeigt, wie viele Stunden dort bleiben, wenn Sie es zurück schaffen.',
    pl: 'Startem może być każda z 6 761 stacji — biorę najbliższą kliknięcia. Kolor kropki mówi, ile godzin tam zostaje, jeśli zdążysz wrócić.',
  },
  'tour.timeline.title': {
    uk: 'День від ранку до ночі',
    en: 'The day from morning to night',
    de: 'Der Tag von früh bis spät',
    pl: 'Dzień od rana do nocy',
  },
  'tour.timeline.text': {
    uk: 'Шкала прокручує добу: станції зʼявляються, коли туди можна доїхати, і гаснуть, коли останній потяг назад уже пішов. Наведіть на станцію — табло вгорі покаже час приїзду й час, коли треба вирушати назад.',
    en: 'The scale runs through the day: stations appear when you can reach them and fade when the last train back has gone. Hover a station and the board above shows the arrival and the time to head back.',
    de: 'Die Skala läuft durch den Tag: Stationen erscheinen, sobald man sie erreicht, und verblassen, wenn der letzte Zug zurück weg ist. Fahren Sie über eine Station — die Anzeige oben zeigt Ankunft und Rückfahrzeit.',
    pl: 'Skala przewija dobę: stacje pojawiają się, gdy da się tam dojechać, i gasną, gdy ostatni pociąg powrotny już odjechał. Najedź na stację — tablica u góry pokaże przyjazd i czas powrotu.',
  },
  'tour.routes.title': {
    uk: 'Маршрут Шелдона',
    en: 'Sheldon’s route',
    de: 'Sheldons Route',
    pl: 'Trasa Sheldona',
  },
  'tour.routes.text': {
    uk: 'Друга історія: поїздка з «Дитинства Шелдона». Три картки перемикають те, що показує карта, — заплановане кільце, реальна поїздка й дорога додому пішки.',
    en: 'The second story: the trip from Young Sheldon. Three cards switch what the map shows — the planned loop, the actual ride and the walk home.',
    de: 'Die zweite Geschichte: die Fahrt aus „Young Sheldon“. Drei Karten schalten um, was die Karte zeigt — die geplante Runde, die tatsächliche Fahrt und den Heimweg zu Fuß.',
    pl: 'Druga historia: podróż z „Młodego Sheldona”. Trzy karty przełączają to, co pokazuje mapa — planowaną pętlę, faktyczny przejazd i drogę do domu pieszo.',
  },
  'tour.sections.title': {
    uk: 'Текст теж керує картою',
    en: 'The text drives the map too',
    de: 'Auch der Text steuert die Karte',
    pl: 'Tekst też steruje mapą',
  },
  'tour.sections.text': {
    uk: 'Клік по будь-якому абзацу показує відповідний маршрут: читаєте про стрілки Франкфурта — карта показує план, читаєте про штрудель — Вайнгайм.',
    en: 'Clicking any paragraph shows the matching route: read about the Frankfurt junctions and the map shows the plan, read about the strudel and it shows Weinheim.',
    de: 'Ein Klick auf einen Absatz zeigt die passende Route: Lesen Sie über die Frankfurter Weichen, zeigt die Karte den Plan; lesen Sie über den Strudel, zeigt sie Weinheim.',
    pl: 'Kliknięcie dowolnego akapitu pokazuje odpowiednią trasę: czytasz o rozjazdach Frankfurtu — mapa pokazuje plan, czytasz o strudlu — Weinheim.',
  },
  'tour.board.title': {
    uk: 'Скрінсейвер',
    en: 'Screensaver',
    de: 'Bildschirmschoner',
    pl: 'Wygaszacz',
  },
  'tour.board.text': {
    uk: 'Третій режим нічого не питає. Годинник іде за реальним часом, а час від часу його місце в тому самому вікні займає або живий потяг із маршрутом, або факт про німецьку залізницю — і знову тиша над картою.',
    en: 'The third mode asks nothing. The clock follows real time, and every so often the same window gives its place to a live train with its route, or to a fact about German railways — and then the map goes quiet again.',
    de: 'Der dritte Modus fragt nichts. Die Uhr folgt der echten Zeit, und ab und zu überlässt dasselbe Fenster seinen Platz einem fahrenden Zug mit seiner Route oder einem Fakt über die deutsche Bahn — danach wird es über der Karte wieder still.',
    pl: 'Trzeci tryb o nic nie pyta. Zegar idzie zgodnie z czasem rzeczywistym, a co jakiś czas to samo okno ustępuje miejsca jadącemu pociągowi z trasą albo faktowi o niemieckiej kolei — i znowu cisza nad mapą.',
  },
  'tour.dots.title': {
    uk: 'Три стани станції',
    en: 'Three states of a station',
    de: 'Drei Zustände einer Station',
    pl: 'Trzy stany stacji',
  },
  'tour.dots.text': {
    uk: 'Крапки на карті різного відтінку: щойно приїхав, стоїть, рушає за півхвилини. Ті самі три числа — тут, у панелі, а під ними дашборди, які оновлюються по одному.',
    en: 'The dots on the map come in three shades: just arrived, standing, leaving in half a minute. The same three numbers are here in the panel, and below them dashboards that refresh one at a time.',
    de: 'Die Punkte auf der Karte haben drei Schattierungen: gerade angekommen, stehend, fährt in einer halben Minute. Dieselben drei Zahlen stehen hier im Panel, darunter Dashboards, die sich einzeln aktualisieren.',
    pl: 'Kropki na mapie mają trzy odcienie: właśnie przyjechał, stoi, odjeżdża za pół minuty. Te same trzy liczby są tu, w panelu, a pod nimi pulpity, które odświeżają się po kolei.',
  },
  'tour.settings.title': {
    uk: 'Що можна крутити',
    en: 'What you can adjust',
    de: 'Was sich einstellen lässt',
    pl: 'Co można pokręcić',
  },
  'tour.settings.text': {
    uk: 'Друга вкладка — налаштування: реальний час або весь день за 10–60 хвилин, потяги з усієї країни чи лише з видимої частини карти, своя область і ритми показу. А панель можна згорнути — лишиться сама карта.',
    en: 'The second tab holds the settings: real time or the whole day in 10–60 minutes, trains from the whole country or only the visible part of the map, your own region, and the rhythm of the show. The panel can also be collapsed — leaving just the map.',
    de: 'Der zweite Tab enthält die Einstellungen: Echtzeit oder der ganze Tag in 10–60 Minuten, Züge aus dem ganzen Land oder nur aus dem sichtbaren Kartenausschnitt, das eigene Bundesland und der Rhythmus der Anzeige. Das Panel lässt sich auch einklappen — dann bleibt nur die Karte.',
    pl: 'Druga zakładka to ustawienia: czas rzeczywisty albo cały dzień w 10–60 minut, pociągi z całego kraju lub tylko z widocznej części mapy, własny region i rytm pokazu. Panel można też zwinąć — zostanie sama mapa.',
  },

  // --- маршрут Шелдона ---
  'story.heading': {
    uk: 'Чому Шелдон насправді втік у німецький потяг',
    en: 'Why Sheldon really ran off to a German train',
    de: 'Warum Sheldon wirklich in einen deutschen Zug floh',
    pl: 'Dlaczego Sheldon naprawdę uciekł do niemieckiego pociągu',
  },
  'story.lead': {
    uk: 'Спойлер: справа не лише в штруделі. Німецька залізниця була для нього раєм на землі, і поїздка з Гейдельберга мала стати дослідженням із чотирьох пунктів.',
    en: 'Spoiler: it was not only about the strudel. German railways were his heaven on earth, and the trip from Heidelberg was meant to be a four-point study.',
    de: 'Spoiler: Es ging nicht nur um den Strudel. Die deutsche Bahn war für ihn das Paradies, und die Fahrt ab Heidelberg sollte eine Untersuchung in vier Punkten werden.',
    pl: 'Spoiler: nie chodziło tylko o strudel. Niemiecka kolej była dla niego rajem na ziemi, a wyjazd z Heidelbergu miał być badaniem w czterech punktach.',
  },
  'story.route.planned.title': {
    uk: 'Що він планував',
    en: 'What he planned',
    de: 'Was er plante',
    pl: 'Co planował',
  },
  'story.route.planned.summary': {
    uk: 'Кільце південним заходом: Гейдельберг — Франкфурт — Штутгарт — Карлсруе — Мангайм.',
    en: 'A loop through the south-west: Heidelberg — Frankfurt — Stuttgart — Karlsruhe — Mannheim.',
    de: 'Eine Runde durch den Südwesten: Heidelberg — Frankfurt — Stuttgart — Karlsruhe — Mannheim.',
    pl: 'Pętla przez południowy zachód: Heidelberg — Frankfurt — Stuttgart — Karlsruhe — Mannheim.',
  },
  'story.route.planned.meta': {
    uk: 'кільце · 5 вузлів',
    en: 'loop · 5 hubs',
    de: 'Runde · 5 Knoten',
    pl: 'pętla · 5 węzłów',
  },
  'story.route.real.title': {
    uk: 'Як вийшло насправді',
    en: 'How it actually went',
    de: 'Wie es wirklich lief',
    pl: 'Jak wyszło naprawdę',
  },
  'story.route.real.summary': {
    uk: 'Одна ділянка до Вайнгайма. Далі речі поїхали у Франкфурт самі.',
    en: 'One leg to Weinheim. After that his luggage went on to Frankfurt alone.',
    de: 'Ein Abschnitt bis Weinheim. Danach fuhr das Gepäck allein nach Frankfurt weiter.',
    pl: 'Jeden odcinek do Weinheim. Dalej bagaż pojechał do Frankfurtu sam.',
  },
  'story.route.real.meta': {
    uk: 'поїздка · 17 км',
    en: 'ride · 17 km',
    de: 'Fahrt · 17 km',
    pl: 'przejazd · 17 km',
  },
  'story.route.walk.title': {
    uk: 'Дорога додому',
    en: 'The way home',
    de: 'Der Heimweg',
    pl: 'Droga do domu',
  },
  'story.route.walk.summary': {
    uk: 'Пішки вздовж доріг від Вайнгайма до Гейдельберга — 22.9 км.',
    en: 'On foot along the roads from Weinheim to Heidelberg — 22.9 km.',
    de: 'Zu Fuß entlang der Straßen von Weinheim nach Heidelberg — 22,9 km.',
    pl: 'Pieszo wzdłuż dróg z Weinheim do Heidelbergu — 22,9 km.',
  },
  'story.route.walk.meta': {
    uk: 'пішки · 22.9 км',
    en: 'on foot · 22.9 km',
    de: 'zu Fuß · 22,9 km',
    pl: 'pieszo · 22,9 km',
  },
  'story.punctuality.title': {
    uk: 'Пункт перший: секундомір',
    en: 'Point one: the stopwatch',
    de: 'Punkt eins: die Stoppuhr',
    pl: 'Punkt pierwszy: stoper',
  },
  'story.punctuality.text': {
    uk: 'Він терпіти не міг американські поїзди, які завжди спізнюються, і збирався довести з секундоміром, що німецькі — найточніші у світі. Іронія в тому, що саме ця точність його й підставила: двері зачинились рівно за графіком і поїзд поїхав без нього.',
    en: 'He could not stand American trains that are always late, and meant to prove with a stopwatch that German ones are the most punctual in the world. The irony is that this very punctuality got him: the doors closed exactly on schedule and the train left without him.',
    de: 'Er konnte amerikanische Züge nicht ausstehen, die immer zu spät sind, und wollte mit der Stoppuhr beweisen, dass deutsche die pünktlichsten der Welt sind. Die Ironie: Genau diese Pünktlichkeit wurde ihm zum Verhängnis — die Türen schlossen fahrplanmäßig, der Zug fuhr ohne ihn.',
    pl: 'Nie znosił amerykańskich pociągów, które zawsze się spóźniają, i zamierzał udowodnić ze stoperem, że niemieckie są najpunktualniejsze na świecie. Ironia w tym, że właśnie ta punktualność go pogrążyła: drzwi zamknęły się dokładnie o czasie i pociąg odjechał bez niego.',
  },
  'story.junctions.title': {
    uk: 'Пункт другий: стрілки Франкфурта',
    en: 'Point two: the Frankfurt junctions',
    de: 'Punkt zwei: die Frankfurter Weichen',
    pl: 'Punkt drugi: rozjazdy Frankfurtu',
  },
  'story.junctions.text': {
    uk: 'Франкфурт — величезний вузол, і Шелдон мріяв знайти міст або вишку, щоб згори замалювати маркером на карті всі стрілки та розвʼязки. Його мозок кайфував від того, як десятки поїздів розʼїжджаються і не стикаються.',
    en: 'Frankfurt is a huge hub, and Sheldon dreamed of finding a bridge or a tower to map every switch and crossing from above with a marker. His brain loved how dozens of trains pass each other and never collide.',
    de: 'Frankfurt ist ein riesiger Knoten, und Sheldon träumte davon, von einer Brücke oder einem Turm aus jede Weiche und Kreuzung mit dem Marker in die Karte zu zeichnen. Sein Gehirn genoss es, wie Dutzende Züge einander ausweichen und nie zusammenstoßen.',
    pl: 'Frankfurt to ogromny węzeł, a Sheldon marzył, by znaleźć most albo wieżę i z góry zaznaczyć markerem na mapie wszystkie rozjazdy. Jego mózg rozkoszował się tym, jak dziesiątki pociągów się mijają i nie zderzają.',
  },
  'story.doppelstock.title': {
    uk: 'Пункт третій: два поверхи',
    en: 'Point three: two decks',
    de: 'Punkt drei: zwei Stockwerke',
    pl: 'Punkt trzeci: dwa piętra',
  },
  'story.doppelstock.text': {
    uk: 'У Техасі він бачив лише товарні вагони, а німецький двоповерховий Doppelstockwagen був для нього технічним дивом: хотів пересісти на такий дорогою до Штутгарта й розібратись, як він тримає рівновагу на швидкості.',
    en: 'In Texas he had only seen freight cars, and the German double-decker Doppelstockwagen was a technical marvel to him: he wanted to change onto one on the way to Stuttgart and work out how it keeps its balance at speed.',
    de: 'In Texas kannte er nur Güterwagen, und der deutsche Doppelstockwagen war für ihn ein technisches Wunder: Auf dem Weg nach Stuttgart wollte er umsteigen und herausfinden, wie er bei Tempo die Balance hält.',
    pl: 'W Teksasie widywał tylko wagony towarowe, a niemiecki piętrowy Doppelstockwagen był dla niego technicznym cudem: chciał się do niego przesiąść w drodze do Stuttgartu i zrozumieć, jak trzyma równowagę przy prędkości.',
  },
  'story.conductor.title': {
    uk: 'Пункт четвертий: кондуктор',
    en: 'Point four: the conductor',
    de: 'Punkt vier: der Schaffner',
    pl: 'Punkt czwarty: konduktor',
  },
  'story.conductor.text': {
    uk: 'Для Шелдона кондуктор — найкраща професія на світі, крутіша за вченого. У вагоні він таки причепився до німецького кондуктора з розпитуваннями. Коли той поскаржився, що від нього пішла дружина, Шелдон утішив: «Зате у вас тепер більше часу на поїзди». Кондуктор назвав його психом і пішов далі.',
    en: 'For Sheldon a conductor has the best job in the world, better than a scientist. On board he did corner a German conductor with questions. When the man complained that his wife had left him, Sheldon consoled him: “But now you have more time for trains.” The conductor called him a nutcase and moved on.',
    de: 'Für Sheldon ist Schaffner der beste Beruf der Welt, besser als Wissenschaftler. Im Wagen nahm er tatsächlich einen deutschen Schaffner in die Zange. Als der klagte, seine Frau habe ihn verlassen, tröstete Sheldon: „Dafür haben Sie jetzt mehr Zeit für Züge.“ Der Schaffner nannte ihn verrückt und ging weiter.',
    pl: 'Dla Sheldona konduktor to najlepszy zawód świata, lepszy niż naukowiec. W wagonie faktycznie zaczepił niemieckiego konduktora pytaniami. Gdy ten poskarżył się, że odeszła od niego żona, Sheldon pocieszył: „Za to ma pan teraz więcej czasu na pociągi”. Konduktor nazwał go świrem i poszedł dalej.',
  },
  'story.strudel.title': {
    uk: 'Вайнгайм: запах штруделя',
    en: 'Weinheim: the smell of strudel',
    de: 'Weinheim: der Duft von Strudel',
    pl: 'Weinheim: zapach strudla',
  },
  'story.strudel.text': {
    uk: 'Тут він вийшов на проміжній станції — і лишився на пероні без речей, документів і грошей. Кіноляп для уважних: штрудель узагалі-то австрійська випічка, і кіоск суто зі штруделями на крихітній німецькій платформі — фантастика. Пахло б там радше брецелями.',
    en: 'Here he stepped off at an intermediate station — and stayed on the platform without luggage, papers or money. A goof for the attentive: strudel is Austrian pastry, and a stall selling only strudel on a tiny German platform is fiction. It would smell of pretzels there.',
    de: 'Hier stieg er an einer Zwischenstation aus — und blieb ohne Gepäck, Papiere und Geld auf dem Bahnsteig. Ein Fehler für Aufmerksame: Strudel ist österreichisches Gebäck, und ein Stand nur mit Strudel auf einem winzigen deutschen Bahnsteig ist Fantasie. Dort röche es eher nach Brezeln.',
    pl: 'Tu wysiadł na stacji pośredniej — i został na peronie bez bagażu, dokumentów i pieniędzy. Wpadka dla uważnych: strudel to wypiek austriacki, a kiosk wyłącznie ze strudlami na malutkim niemieckim peronie to fantazja. Pachniałoby tam raczej preclami.',
  },
  'story.walk.title': {
    uk: 'І 22.9 кілометрів пішки',
    en: 'And 22.9 kilometres on foot',
    de: 'Und 22,9 Kilometer zu Fuß',
    pl: 'I 22,9 kilometra pieszo',
  },
  'story.walk.text': {
    uk: 'Речі доїхали до Франкфурта, а Шелдон пішов додому вздовж траси. У серії звучить «18 кілометрів» — саме стільки між вокзалами по прямій, а дорогами виходить 22.9. Тут ця дорога прокладена по справжніх дорогах, а не намальована лінійкою. Регіональний поїзд долає ту саму відстань за чверть години.',
    en: 'The luggage reached Frankfurt while Sheldon walked home along the road. The episode says “18 kilometres” — that is the straight line between the stations; by road it comes to 22.9. Here the walk follows real roads rather than a ruler. A regional train covers the same distance in a quarter of an hour.',
    de: 'Das Gepäck erreichte Frankfurt, Sheldon lief die Straße entlang nach Hause. In der Folge heißt es „18 Kilometer“ — so weit ist es Luftlinie zwischen den Bahnhöfen; über Straßen sind es 22,9. Hier folgt der Weg echten Straßen statt dem Lineal. Ein Regionalzug schafft dieselbe Strecke in einer Viertelstunde.',
    pl: 'Bagaż dojechał do Frankfurtu, a Sheldon poszedł do domu wzdłuż drogi. W odcinku pada „18 kilometrów” — tyle jest w linii prostej między dworcami, drogami wychodzi 22,9. Tutaj ta trasa biegnie prawdziwymi drogami, a nie linijką. Pociąg regionalny pokonuje ten dystans w kwadrans.',
  },

  // --- факти про німецьку залізницю ---
  'fact.00': {
    uk: 'Мережа Німеччини — 33 399 км колій (2022). Шоста у світі й найбільша в Євросоюзі. Для порівняння: це майже вісім разів по відстані від Києва до Лісабона.',
    en: 'Germany’s network is 33,399 km of track (2022). Sixth in the world and the largest in the EU. For scale: that is almost eight times the distance from Kyiv to Lisbon.',
    de: 'Deutschlands Netz umfasst 33 399 km Gleis (2022). Weltweit Platz sechs und das größte in der EU. Zum Vergleich: fast achtmal die Strecke von Kyjiw nach Lissabon.',
    pl: 'Sieć Niemiec to 33 399 km torów (2022). Szósta na świecie i największa w UE. Dla porównania: to prawie osiem razy odległość z Kijowa do Lizbony.',
  },
  'fact.01': {
    uk: 'Електрифіковано 20 540 км — змінним струмом 15 кВ і частотою 16⅔ Гц, а не звичними 50. Ця частота — спадок початку XX століття, коли тягові двигуни не терпіли промислових 50 герц.',
    en: '20,540 km are electrified — with 15 kV at 16⅔ Hz, not the usual 50. That frequency is a legacy of the early 20th century, when traction motors could not cope with industrial 50 Hz.',
    de: '20 540 km sind elektrifiziert — mit 15 kV bei 16⅔ Hz statt der üblichen 50. Diese Frequenz stammt aus dem frühen 20. Jahrhundert, als Fahrmotoren mit industriellen 50 Hz nicht zurechtkamen.',
    pl: 'Zelektryfikowano 20 540 km — prądem 15 kV o częstotliwości 16⅔ Hz zamiast zwykłych 50. Ta częstotliwość to spadek po początku XX wieku, gdy silniki trakcyjne nie radziły sobie z przemysłowymi 50 Hz.',
  },
  'fact.02': {
    uk: 'Двоколійних ділянок 18 556 км: більша половина мережі вміє пропускати зустрічні потяги без роз’їздів. Решта — одноколійні гілки, де розклад тримається на роз’їздах і точності до хвилини.',
    en: '18,556 km are double-track: over half the network can pass opposing trains without a siding. The rest are single-track branches where the timetable hangs on passing loops and minute-perfect timing.',
    de: '18 556 km sind zweigleisig: Über die Hälfte des Netzes kommt ohne Ausweichstellen aus. Der Rest sind eingleisige Strecken, wo der Fahrplan an Ausweichstellen und Minutengenauigkeit hängt.',
    pl: '18 556 km jest dwutorowych: ponad połowa sieci mija pociągi bez mijanek. Reszta to linie jednotorowe, gdzie rozkład trzyma się na mijankach i punktualności co do minuty.',
  },
  'fact.03': {
    uk: 'Швидкісних ліній у країні 1 658 км — це менше п’яти відсотків мережі. Саме тому ICE більшу частину шляху їде звичайними лініями, ділячи їх із регіональними потягами.',
    en: 'High-speed lines total 1,658 km — under five per cent of the network. That is why an ICE spends most of its run on ordinary lines, sharing them with regional trains.',
    de: 'Schnellfahrstrecken machen 1 658 km aus — keine fünf Prozent des Netzes. Deshalb fährt ein ICE den größten Teil seines Laufs auf normalen Strecken, gemeinsam mit Regionalzügen.',
    pl: 'Linii dużych prędkości jest 1 658 km — mniej niż pięć procent sieci. Dlatego ICE większość trasy jedzie zwykłymi liniami, dzieląc je z pociągami regionalnymi.',
  },
  'fact.04': {
    uk: 'У 2018-му потягами зробили 2,87 мільярда поїздок. На кожного жителя — по 34 за рік. Це приблизно вісім мільйонів поїздок щодня — по одній на кожного жителя Берліна й Мюнхена разом.',
    en: 'In 2018 trains carried 2.87 billion journeys — 34 a year per inhabitant. That is about eight million journeys a day — one for every resident of Berlin and Munich combined.',
    de: '2018 gab es 2,87 Milliarden Bahnfahrten — 34 pro Einwohner und Jahr. Das sind rund acht Millionen Fahrten pro Tag — eine für jeden Einwohner Berlins und Münchens zusammen.',
    pl: 'W 2018 roku odbyto 2,87 miliarda podróży — po 34 na mieszkańca rocznie. To około osiem milionów podróży dziennie — po jednej na każdego mieszkańca Berlina i Monachium razem.',
  },
  'fact.05': {
    uk: 'Пасажирообіг за 2018 рік — 97,8 мільярда пасажиро-кілометрів. У середньому це 34-кілометрова поїздка на кожного жителя щомісяця.',
    en: 'Passenger traffic in 2018: 97.8 billion passenger-kilometres. On average that is a 34-kilometre trip per inhabitant every month.',
    de: 'Verkehrsleistung 2018: 97,8 Milliarden Personenkilometer. Im Schnitt ist das eine 34-Kilometer-Fahrt pro Einwohner und Monat.',
    pl: 'Praca przewozowa w 2018: 97,8 miliarda pasażerokilometrów. Średnio to 34-kilometrowa podróż na mieszkańca miesięcznie.',
  },
  'fact.06': {
    uk: 'Вантажів за 2018 рік — 116 мільярдів тонно-кілометрів. Вантажний потяг знімає з автобанів приблизно п’ятдесят фур — і саме тому колія лишається дешевшою за асфальт.',
    en: 'Freight in 2018: 116 billion tonne-kilometres. One freight train takes about fifty lorries off the autobahn — which is why rail stays cheaper than asphalt.',
    de: 'Güterverkehr 2018: 116 Milliarden Tonnenkilometer. Ein Güterzug nimmt rund fünfzig Lastwagen von der Autobahn — deshalb bleibt die Schiene billiger als Asphalt.',
    pl: 'Towary w 2018: 116 miliardów tonokilometrów. Jeden pociąg towarowy zdejmuje z autostrady około pięćdziesięciu ciężarówek — dlatego szyna zostaje tańsza niż asfalt.',
  },
  'fact.07': {
    uk: 'У мережі 1 079 тунелів загальною довжиною 168 кілометрів. Найдовший із них — Ландрюкентунель на швидкісній лінії Ганновер — Вюрцбург, майже одинадцять кілометрів.',
    en: 'The network holds 1,079 tunnels with a combined length of 168 kilometres. The longest of them is the Landrücken tunnel on the Hanover — Würzburg high-speed line, nearly eleven kilometres.',
    de: 'Im Netz liegen 1 079 Tunnel mit zusammen 168 Kilometern Länge. Der längste ist der Landrückentunnel an der Schnellfahrstrecke Hannover — Würzburg mit knapp elf Kilometern.',
    pl: 'W sieci jest 1 079 tuneli o łącznej długości 168 kilometrów. Najdłuższy z nich to tunel Landrücken na linii dużych prędkości Hanower — Würzburg, prawie jedenaście kilometrów.',
  },
  'fact.08': {
    uk: 'Залізничних операторів у Німеччині 452 (станом на жовтень 2016). Deutsche Bahn — лише найбільший із них. Решта — приватні перевізники, які виграють регіональні конкурси й возять пасажирів під місцевими брендами.',
    en: 'Germany has 452 registered railway operators (as of October 2016). Deutsche Bahn is merely the largest. The rest are private operators that win regional tenders and carry passengers under local brands.',
    de: 'Deutschland zählt 452 registrierte Eisenbahnunternehmen (Stand Oktober 2016). Die Deutsche Bahn ist nur das größte. Der Rest sind private Betreiber, die Regionalausschreibungen gewinnen und unter lokalen Marken fahren.',
    pl: 'W Niemczech działa 452 zarejestrowanych przewoźników kolejowych (stan na październik 2016). Deutsche Bahn to tylko największy z nich. Reszta to prywatni przewoźnicy, którzy wygrywają regionalne przetargi i wożą pasażerów pod lokalnymi markami.',
  },
  'fact.09': {
    uk: 'Регіональні перевезення на дві третини належать DB Regio: 67% ринку у 2016 році. Землі замовляють ці перевезення самі, тому в сусідніх регіонах на однакових коліях можуть їздити різні компанії.',
    en: 'Two thirds of regional services belong to DB Regio: 67% of the market in 2016. The states order these services themselves, so neighbouring regions can have different companies on the same tracks.',
    de: 'Zwei Drittel des Regionalverkehrs entfallen auf DB Regio: 67 % Marktanteil 2016. Die Länder bestellen diese Leistungen selbst, deshalb fahren in Nachbarregionen auf denselben Gleisen verschiedene Unternehmen.',
    pl: 'Dwie trzecie przewozów regionalnych należy do DB Regio: 67% rynku w 2016 roku. Kraje związkowe same zamawiają te przewozy, więc w sąsiednich regionach po tych samych torach jeżdżą różne firmy.',
  },
  'fact.10': {
    uk: 'Дотації покривали 25,6% витрат приміського сполучення у 2018 році. Квиток покриває три чверті — решту докладає бюджет, бо приміський потяг вважають комунальною послугою, а не бізнесом.',
    en: 'Subsidies covered 25.6% of the cost of local services in 2018. Fares cover three quarters; the budget adds the rest, because local trains count as a public service, not a business.',
    de: 'Zuschüsse deckten 2018 25,6 % der Kosten des Nahverkehrs. Fahrkarten decken drei Viertel, den Rest zahlt der Haushalt — Nahverkehr gilt als Daseinsvorsorge, nicht als Geschäft.',
    pl: 'Dotacje pokrywały 25,6% kosztów przewozów lokalnych w 2018 roku. Bilety pokrywają trzy czwarte, resztę dokłada budżet — pociąg podmiejski to usługa publiczna, a nie biznes.',
  },
  'fact.11': {
    uk: 'Перша парова залізниця Німеччини відкрилась 7 грудня 1835 року: шість кілометрів між Нюрнбергом і Фюртом. Сьогодні цю відстань проїжджає метро за десять хвилин, а тоді вона здавалась подвигом.',
    en: 'Germany’s first steam railway opened on 7 December 1835: six kilometres between Nuremberg and Fürth. Today the U-Bahn covers that distance in ten minutes; back then it looked like a feat.',
    de: 'Deutschlands erste Dampfeisenbahn wurde am 7. Dezember 1835 eröffnet: sechs Kilometer zwischen Nürnberg und Fürth. Heute schafft die U-Bahn diese Strecke in zehn Minuten; damals galt sie als Wagnis.',
    pl: 'Pierwsza parowa kolej Niemiec ruszyła 7 grudnia 1835 roku: sześć kilometrów między Norymbergą a Fürth. Dziś metro pokonuje ten dystans w dziesięć minut; wtedy wydawał się wyczynem.',
  },
  'fact.12': {
    uk: 'Локомотив «Адлер» для першої лінії привезли з Ньюкасла, з майстерні Джорджа Стефенсона. Спершу він робив лише два рейси на день — о 13:00 і о 14:00, решту тягнули коні. Машиніста теж привезли з Англії — німецького ще не було кому вивчити.',
    en: 'The Adler locomotive for that first line came from Newcastle, from George Stephenson’s works. At first it ran only twice a day — at 13:00 and 14:00; horses pulled the rest. The driver came from England too — there was nobody in Germany yet to train one.',
    de: 'Die Lokomotive „Adler“ für diese erste Linie kam aus Newcastle, aus George Stephensons Werkstatt. Anfangs fuhr sie nur zweimal täglich — um 13 und 14 Uhr; den Rest zogen Pferde. Auch der Lokführer kam aus England — in Deutschland konnte ihn noch niemand ausbilden.',
    pl: 'Lokomotywę „Adler” dla tej pierwszej linii sprowadzono z Newcastle, z warsztatu George’a Stephensona. Początkowo jeździła tylko dwa razy dziennie — o 13:00 i 14:00, resztę ciągnęły konie. Maszynistę też sprowadzono z Anglii — w Niemczech nie miał go kto wyszkolić.',
  },
  'fact.13': {
    uk: 'Перша далека лінія — Лейпциг — Дрезден, 7 квітня 1839 року. Сто двадцять кілометрів між двома саксонськими містами тоді долали за дев’ять годин.',
    en: 'The first long-distance line was Leipzig — Dresden, 7 April 1839. The hundred and twenty kilometres between the two Saxon cities took nine hours back then.',
    de: 'Die erste Fernstrecke war Leipzig — Dresden, 7. April 1839. Die hundertzwanzig Kilometer zwischen den beiden sächsischen Städten dauerten damals neun Stunden.',
    pl: 'Pierwsza linia dalekobieżna to Lipsk — Drezno, 7 kwietnia 1839 roku. Sto dwadzieścia kilometrów między dwoma saksońskimi miastami pokonywano wtedy w dziewięć godzin.',
  },
  'fact.14': {
    uk: 'У 1845 році в країні було 2 000 км колій, за десять років — уже понад 8 000. Залізниця росла швидше за телеграф: колія була головним способом швидко доставити хоч людину, хоч звістку.',
    en: 'By 1845 the country had 2,000 km of track; ten years later, over 8,000. Rail grew faster than the telegraph: track was the quickest way to move either a person or a message.',
    de: '1845 hatte das Land 2 000 km Gleis, zehn Jahre später über 8 000. Die Bahn wuchs schneller als der Telegraf: Das Gleis war der schnellste Weg für Menschen wie für Nachrichten.',
    pl: 'W 1845 roku kraj miał 2 000 km torów, dziesięć lat później ponad 8 000. Kolej rosła szybciej niż telegraf: tor był najszybszym sposobem przewiezienia i człowieka, i wiadomości.',
  },
  'fact.15': {
    uk: 'До 1880 року німецькі залізниці мали 9 400 локомотивів. Кожен із них треба було вручну заправити вугіллям і водою — звідси і мережа водонапірних веж уздовж колій.',
    en: 'By 1880 German railways owned 9,400 locomotives. Each had to be fed coal and water by hand — hence the network of water towers along the lines.',
    de: 'Bis 1880 besaßen die deutschen Bahnen 9 400 Lokomotiven. Jede musste von Hand mit Kohle und Wasser versorgt werden — daher die Wassertürme entlang der Strecken.',
    pl: 'Do 1880 roku niemieckie koleje miały 9 400 lokomotyw. Każdą trzeba było ręcznie zaopatrzyć w węgiel i wodę — stąd sieć wież ciśnień wzdłuż torów.',
  },
  'fact.16': {
    uk: '1 квітня 1920 року землі віддали свої залізниці в одні руки — так з’явилась Deutsche Reichseisenbahnen. До того кожне королівство мало власну залізницю, власні тарифи й власні уявлення про розклад.',
    en: 'On 1 April 1920 the states handed their railways to one owner — the Deutsche Reichseisenbahnen. Until then every kingdom had its own railway, its own fares and its own idea of a timetable.',
    de: 'Am 1. April 1920 gaben die Länder ihre Bahnen in eine Hand — so entstanden die Deutschen Reichseisenbahnen. Bis dahin hatte jedes Königreich eine eigene Bahn, eigene Tarife und eigene Vorstellungen vom Fahrplan.',
    pl: '1 kwietnia 1920 roku kraje związkowe oddały swoje koleje w jedne ręce — tak powstały Deutsche Reichseisenbahnen. Do tego czasu każde królestwo miało własną kolej, własne taryfy i własne pojęcie o rozkładzie.',
  },
  'fact.17': {
    uk: '1 січня 1994 року західну Бундесбан і східну Райхсбан злили в Deutsche Bahn — через чотири роки після обʼєднання країни. Об’єднання забрало чотири роки: у двох мережах різнились не лише тарифи, а й сигналізація та правила руху.',
    en: 'On 1 January 1994 the western Bundesbahn and the eastern Reichsbahn merged into Deutsche Bahn — four years after reunification. The merger took four years: the two networks differed not only in fares but in signalling and operating rules.',
    de: 'Am 1. Januar 1994 verschmolzen die westliche Bundesbahn und die östliche Reichsbahn zur Deutschen Bahn — vier Jahre nach der Wiedervereinigung. Die Fusion dauerte vier Jahre: Die beiden Netze unterschieden sich nicht nur in den Tarifen, sondern auch in Signaltechnik und Betriebsregeln.',
    pl: '1 stycznia 1994 roku zachodnią Bundesbahn i wschodnią Reichsbahn połączono w Deutsche Bahn — cztery lata po zjednoczeniu. Połączenie zajęło cztery lata: sieci różniły się nie tylko taryfami, ale i sygnalizacją oraz przepisami ruchu.',
  },
  'fact.18': {
    uk: 'Метро в Німеччині є лише в чотирьох містах: Берлін, Гамбург, Мюнхен і Нюрнберг. Решта великих міст обходиться S-Bahn і трамваями — підземка вважалась надто дорогою для мільйонника.',
    en: 'Only four German cities have a U-Bahn: Berlin, Hamburg, Munich and Nuremberg. Other big cities make do with S-Bahn and trams — a metro was considered too expensive below a million people.',
    de: 'Nur vier deutsche Städte haben eine U-Bahn: Berlin, Hamburg, München und Nürnberg. Andere Großstädte kommen mit S-Bahn und Straßenbahn aus — eine U-Bahn galt unter einer Million Einwohnern als zu teuer.',
    pl: 'Metro ma tylko cztery niemieckie miasta: Berlin, Hamburg, Monachium i Norymberga. Inne duże miasta radzą sobie S-Bahnem i tramwajami — metro uznawano za zbyt drogie poniżej miliona mieszkańców.',
  },
  'fact.19': {
    uk: 'Улітку 2022-го, у розпал енергетичної кризи, три місяці діяв квиток за 9 євро на всю країну. За три місяці продали 52 мільйони квитків, а потяги в вихідні виглядали як концертний майданчик.',
    en: 'In the summer of 2022, at the height of the energy crisis, a nine-euro nationwide ticket ran for three months. Fifty-two million tickets sold in three months, and weekend trains looked like a festival crowd.',
    de: 'Im Sommer 2022, mitten in der Energiekrise, galt drei Monate lang das 9-Euro-Ticket für das ganze Land. In drei Monaten wurden 52 Millionen Tickets verkauft, und die Wochenendzüge glichen einem Festivalgelände.',
    pl: 'Latem 2022, w szczycie kryzysu energetycznego, przez trzy miesiące obowiązywał bilet za 9 euro na cały kraj. W trzy miesiące sprzedano 52 miliony biletów, a weekendowe pociągi wyglądały jak koncertowy tłum.',
  },
  'fact.20': {
    uk: 'Deutschlandticket — 63 євро на місяць за весь регіональний транспорт країни (ціна на січень 2026). Він працює в усіх регіональних потягах, автобусах і трамваях країни — але не в ICE.',
    en: 'The Deutschlandticket costs 63 euros a month for all regional transport in the country (price as of January 2026). It works on every regional train, bus and tram in the country — but not on the ICE.',
    de: 'Das Deutschlandticket kostet 63 Euro im Monat für den gesamten Nahverkehr des Landes (Stand Januar 2026). Es gilt in allen Regionalzügen, Bussen und Straßenbahnen des Landes — nur nicht im ICE.',
    pl: 'Deutschlandticket kosztuje 63 euro miesięcznie za cały transport regionalny w kraju (cena na styczeń 2026). Działa we wszystkich pociągach regionalnych, autobusach i tramwajach kraju — ale nie w ICE.',
  },
  'fact.21': {
    uk: 'Попередники залізниць — рейкові вози з нереборними колесами — їздили німецькими копальнями ще у XVI столітті. Вагонетки тягнули коні або самі гірники, а рейки були дерев’яними — залізо прийшло значно пізніше.',
    en: 'The ancestors of railways — wagonways with unflanged wheels — ran in German mines back in the 16th century. Horses or the miners themselves pulled the carts, and the rails were wooden — iron came much later.',
    de: 'Die Vorläufer der Eisenbahn — Spurbahnen mit ungeflanschten Rädern — fuhren schon im 16. Jahrhundert in deutschen Bergwerken. Pferde oder die Bergleute selbst zogen die Wagen, die Schienen waren aus Holz — Eisen kam viel später.',
    pl: 'Poprzednicy kolei — wozy szynowe z kołami bez obrzeży — jeździły w niemieckich kopalniach już w XVI wieku. Wozy ciągnęły konie albo sami górnicy, a szyny były drewniane — żelazo przyszło znacznie później.',
  },
  'fact.22': {
    uk: 'Штаб-квартира Deutsche Bahn — башта Bahntower на Потсдамській площі в Берліні. Вежу збудували в 2000 році над самим вокзалом Потсдамер Плац — керівництво їздить на роботу власними потягами.',
    en: 'Deutsche Bahn’s headquarters is the Bahntower on Potsdamer Platz in Berlin. The tower went up in 2000 right above Potsdamer Platz station — management commutes on its own trains.',
    de: 'Der Sitz der Deutschen Bahn ist der Bahntower am Potsdamer Platz in Berlin. Der Turm entstand 2000 direkt über dem Bahnhof Potsdamer Platz — die Führung pendelt mit den eigenen Zügen.',
    pl: 'Siedziba Deutsche Bahn to Bahntower na Potsdamer Platz w Berlinie. Wieżę zbudowano w 2000 roku tuż nad dworcem Potsdamer Platz — zarząd dojeżdża własnymi pociągami.',
  },
  'fact.23': {
    uk: 'У Deutsche Bahn 211 тисяч працівників у Німеччині й 338 тисяч по світу. Це більше, ніж живе в Карлсруе, і робить DB одним із найбільших роботодавців країни.',
    en: 'Deutsche Bahn employs 211,000 people in Germany and 338,000 worldwide. That is more people than live in Karlsruhe, making DB one of the country’s largest employers.',
    de: 'Die Deutsche Bahn beschäftigt 211 000 Menschen in Deutschland und 338 000 weltweit. Das sind mehr Menschen, als in Karlsruhe leben — die DB ist einer der größten Arbeitgeber des Landes.',
    pl: 'Deutsche Bahn zatrudnia 211 tysięcy osób w Niemczech i 338 tysięcy na świecie. To więcej, niż mieszka w Karlsruhe, co czyni DB jednym z największych pracodawców kraju.',
  },
  'fact.24': {
    uk: 'Виторг Deutsche Bahn за 2022 рік — 56,3 мільярда євро, чистий прибуток — 227 мільйонів. Прибуток становить менше половини відсотка від виторгу: залізниця тримається не на марджі, а на обороті й дотаціях.',
    en: 'Deutsche Bahn’s 2022 revenue was 56.3 billion euros, with a net profit of 227 million. Profit is under half a per cent of revenue: the railway lives on turnover and subsidies, not margins.',
    de: 'Der Umsatz der Deutschen Bahn lag 2022 bei 56,3 Milliarden Euro, der Gewinn bei 227 Millionen. Der Gewinn liegt unter einem halben Prozent des Umsatzes: Die Bahn lebt von Umsatz und Zuschüssen, nicht von der Marge.',
    pl: 'Przychód Deutsche Bahn w 2022 roku to 56,3 miliarda euro, zysk netto — 227 milionów. Zysk to mniej niż pół procenta przychodu: kolej żyje z obrotu i dotacji, a nie z marży.',
  },
  'fact.25': {
    uk: 'У 2022 році далекими потягами проїхали 132 мільйони пасажирів, регіональними — 1,6 мільярда. Тобто на кожного далекого пасажира припадає дванадцять регіональних — країна їздить переважно недалеко.',
    en: 'In 2022 long-distance trains carried 132 million passengers, regional ones 1.6 billion. That is twelve regional passengers for every long-distance one — the country mostly travels short.',
    de: '2022 fuhren 132 Millionen Fahrgäste im Fernverkehr und 1,6 Milliarden im Regionalverkehr. Auf jeden Fernreisenden kommen zwölf Regionalfahrgäste — das Land fährt vor allem kurz.',
    pl: 'W 2022 roku pociągami dalekobieżnymi przejechało 132 miliony pasażerów, regionalnymi — 1,6 miliarda. Na każdego pasażera dalekobieżnego przypada dwunastu regionalnych — kraj jeździ głównie krótko.',
  },
  'fact.26': {
    uk: 'Вантажне крило DB перевезло 222 мільйони тонн за 2022 рік. Воно ж возить британський королівський потяг. Королівський потяг возять на замовлення британців: своїх локомотивів під таке навантаження в них немає.',
    en: 'DB’s freight arm moved 222 million tonnes in 2022. It also hauls the British Royal Train. The Royal Train is hauled to British order: they have no locomotives of their own for the job.',
    de: 'Die Gütersparte der DB beförderte 2022 222 Millionen Tonnen. Sie zieht auch den britischen Royal Train. Der Royal Train wird im britischen Auftrag gezogen: eigene Loks dafür gibt es dort nicht.',
    pl: 'Towarowe ramię DB przewiozło 222 miliony ton w 2022 roku. Ono też ciągnie brytyjski pociąg królewski. Pociąg królewski ciągną na zlecenie Brytyjczyków: własnych lokomotyw do tego nie mają.',
  },
  'fact.27': {
    uk: 'Світовий рекорд швидкості 406,9 км/год потяг InterCityExperimental поставив 1 травня 1988 року. Рекорд протримався три роки, поки його не забрав французький TGV — і відтоді Німеччина за швидкістю не ганяється.',
    en: 'The InterCityExperimental set the world speed record of 406.9 km/h on 1 May 1988. The record stood for three years until the French TGV took it — and Germany has not chased speed since.',
    de: 'Der InterCityExperimental stellte am 1. Mai 1988 den Weltrekord von 406,9 km/h auf. Der Rekord hielt drei Jahre, bis ihn der französische TGV holte — seither jagt Deutschland der Geschwindigkeit nicht mehr nach.',
    pl: 'InterCityExperimental ustanowił rekord świata 406,9 km/h 1 maja 1988 roku. Rekord utrzymał się trzy lata, aż zabrał go francuski TGV — od tego czasu Niemcy nie gonią za prędkością.',
  },
  'fact.28': {
    uk: 'Регулярний ICE поїхав 2 червня 1991 року — між Гамбургом і Мюнхеном. Перша лінія повторила маршрут, яким за сто років до того їздили перші експреси — тільки вдвічі швидше.',
    en: 'Scheduled ICE service began on 2 June 1991 — between Hamburg and Munich. The first line repeated a route the earliest expresses had run a century before — only twice as fast.',
    de: 'Der planmäßige ICE-Verkehr begann am 2. Juni 1991 — zwischen Hamburg und München. Die erste Linie folgte einer Strecke, auf der ein Jahrhundert zuvor die ersten Schnellzüge fuhren — nur doppelt so schnell.',
    pl: 'Regularne kursy ICE ruszyły 2 czerwca 1991 roku — między Hamburgiem a Monachium. Pierwsza linia powtórzyła trasę, którą sto lat wcześniej jeździły pierwsze ekspresy — tylko dwa razy szybciej.',
  },
  'fact.29': {
    uk: 'Парк ICE — понад 350 составів; у роботі вони тримають до 330 км/год. Проєктна швидкість вища, але розклад рахують під реальні лінії, де 330 бувають лише на кількох відрізках.',
    en: 'The ICE fleet numbers over 350 trainsets; in service they hold up to 330 km/h. The design speed is higher, but timetables are built for real lines, where 330 happens on a few stretches only.',
    de: 'Die ICE-Flotte umfasst über 350 Züge; im Betrieb fahren sie bis zu 330 km/h. Die Bauartgeschwindigkeit ist höher, doch der Fahrplan rechnet mit echten Strecken, wo 330 nur auf wenigen Abschnitten möglich sind.',
    pl: 'Flota ICE to ponad 350 składów; w ruchu utrzymują do 330 km/h. Prędkość konstrukcyjna jest wyższa, ale rozkład liczy się pod realne linie, gdzie 330 zdarza się na kilku odcinkach.',
  },
  'fact.30': {
    uk: 'Найбільший вокзал Європи за площею — Лейпциг: 83 460 квадратних метрів. Це приблизно дванадцять футбольних полів під одним дахом — і при цьому вокзал тупиковий.',
    en: 'Europe’s largest station by floor area is Leipzig: 83,460 square metres. That is about twelve football pitches under one roof — and it is a terminus at that.',
    de: 'Europas flächengrößter Bahnhof ist Leipzig: 83 460 Quadratmeter. Das sind rund zwölf Fußballfelder unter einem Dach — und dabei ist es ein Kopfbahnhof.',
    pl: 'Największy dworzec Europy pod względem powierzchni to Lipsk: 83 460 metrów kwadratowych. To około dwunastu boisk piłkarskich pod jednym dachem — i to dworzec czołowy.',
  },
  'fact.31': {
    uk: 'У Лейпцига 21 наземна платформа під шістьма чавунними навісами й ще дві в міському тунелі, відкритому в грудні 2013 року. Тунель зробив тупиковий вокзал прохідним для міських потягів, не чіпаючи історичних навісів.',
    en: 'Leipzig has 21 surface platforms under six iron sheds, plus two more in the city tunnel opened in December 2013. The tunnel made the terminus a through station for city trains without touching the historic sheds.',
    de: 'Leipzig hat 21 oberirdische Bahnsteige unter sechs eisernen Hallen und zwei weitere im City-Tunnel, eröffnet im Dezember 2013. Der Tunnel machte den Kopfbahnhof für S-Bahnen zum Durchgangsbahnhof, ohne die historischen Hallen anzutasten.',
    pl: 'Lipsk ma 21 peronów naziemnych pod sześcioma żelaznymi halami i jeszcze dwa w tunelu miejskim otwartym w grudniu 2013 roku. Tunel zamienił dworzec czołowy w przelotowy dla pociągów miejskich, nie ruszając historycznych hal.',
  },
  'fact.32': {
    uk: 'Будівлю лейпцизького вокзалу завершили 4 грудня 1915 року — з 26 коліями це був один із найбільших вокзалів світу. Дві залізничні компанії будували його разом і кожна хотіла власний вхід — тому фасад має два симетричні вестибюлі.',
    en: 'The Leipzig station building was finished on 4 December 1915 — with 26 tracks it was one of the largest in the world. Two railway companies built it together and each wanted its own entrance — hence the two symmetrical halls.',
    de: 'Das Leipziger Empfangsgebäude wurde am 4. Dezember 1915 fertig — mit 26 Gleisen einer der größten Bahnhöfe der Welt. Zwei Bahngesellschaften bauten ihn gemeinsam, jede wollte einen eigenen Eingang — daher die zwei symmetrischen Hallen.',
    pl: 'Budynek dworca w Lipsku ukończono 4 grudnia 1915 roku — z 26 torami był jednym z największych na świecie. Budowały go dwie spółki kolejowe i każda chciała własne wejście — stąd dwa symetryczne westybule.',
  },
  'fact.33': {
    uk: 'Лейпциг приймає близько 120 тисяч пасажирів на добу, а у 2021 році його визнали найкращим вокзалом Європи. Усередині — двоповерхова галерея крамниць, тому вокзал працює як торговий центр із коліями.',
    en: 'Leipzig handles about 120,000 passengers a day, and in 2021 it was named Europe’s best station. Inside there is a two-storey shopping gallery, so the station doubles as a mall with tracks.',
    de: 'Leipzig zählt rund 120 000 Reisende pro Tag und wurde 2021 zum besten Bahnhof Europas gekürt. Im Inneren liegt eine zweigeschossige Ladenpassage — der Bahnhof funktioniert als Einkaufszentrum mit Gleisen.',
    pl: 'Lipsk przyjmuje około 120 tysięcy pasażerów dziennie, a w 2021 roku uznano go za najlepszy dworzec Europy. W środku jest dwupoziomowa galeria sklepów, więc dworzec działa jak centrum handlowe z torami.',
  },
  'fact.34': {
    uk: 'Головних вокзалів — тих самих Hauptbahnhof — у Німеччині рівно 122. Назва не гарантує розміру: є Hauptbahnhof із двома платформами, бо в місті просто немає інших станцій.',
    en: 'Germany has exactly 122 stations called Hauptbahnhof. The name guarantees nothing about size: some Hauptbahnhöfe have two platforms, simply because the town has no other station.',
    de: 'In Deutschland gibt es genau 122 Bahnhöfe namens Hauptbahnhof. Der Name sagt nichts über die Größe: Manche Hauptbahnhöfe haben zwei Bahnsteige, weil es im Ort keinen anderen gibt.',
    pl: 'W Niemczech jest dokładnie 122 dworce zwane Hauptbahnhof. Nazwa nie gwarantuje wielkości: są Hauptbahnhof z dwoma peronami, bo w mieście nie ma innych stacji.',
  },
  'fact.35': {
    uk: 'Найзавантаженіший вокзал країни — Гамбург: від 480 до 550 тисяч пасажирів щодня. У Європі він другий після паризького Північного. Через нього щодня проходить понад сімсот потягів, і майже кожен другий — приміський.',
    en: 'The country’s busiest station is Hamburg: 480,000 to 550,000 passengers a day. In Europe it is second after Paris Nord. More than seven hundred trains a day pass through, and almost every second one is a commuter service.',
    de: 'Der meistfrequentierte Bahnhof des Landes ist Hamburg: 480 000 bis 550 000 Reisende täglich. In Europa Platz zwei hinter dem Gare du Nord. Täglich fahren über siebenhundert Züge hindurch, fast jeder zweite ist ein Nahverkehrszug.',
    pl: 'Najruchliwszy dworzec kraju to Hamburg: od 480 do 550 tysięcy pasażerów dziennie. W Europie drugi po paryskim Gare du Nord. Przejeżdża przez niego ponad siedemset pociągów dziennie, prawie co drugi to pociąg podmiejski.',
  },
  'fact.36': {
    uk: 'Гамбурзький вокзал відкрили 1906 року; його зал із заліза і скла — 206 метрів завдовжки. Під час війни зал вигорів, і його відбудували за довоєнними кресленнями — рідкісний випадок для німецьких вокзалів.',
    en: 'Hamburg’s station opened in 1906; its iron-and-glass hall is 206 metres long. The hall burned out in the war and was rebuilt to prewar drawings — a rare thing for German stations.',
    de: 'Der Hamburger Hauptbahnhof wurde 1906 eröffnet; seine Halle aus Eisen und Glas ist 206 Meter lang. Im Krieg brannte die Halle aus und wurde nach Vorkriegsplänen wieder aufgebaut — bei deutschen Bahnhöfen selten.',
    pl: 'Dworzec w Hamburgu otwarto w 1906 roku; jego hala z żelaza i szkła ma 206 metrów długości. W czasie wojny hala spłonęła i odbudowano ją według przedwojennych rysunków — rzadkość wśród niemieckich dworców.',
  },
  'fact.37': {
    uk: 'Франкфурт має 24 наземні платформи й близько 493 тисяч пасажирів на добу — друге місце в країні. Під наземними платформами лежать ще чотири підземні — для міських потягів, які йдуть далі під центром.',
    en: 'Frankfurt has 24 surface platforms and about 493,000 passengers a day — second in the country. Beneath the surface platforms lie four more underground, for city trains carrying on below the centre.',
    de: 'Frankfurt hat 24 oberirdische Bahnsteige und rund 493 000 Reisende täglich — Platz zwei im Land. Unter den oberirdischen Bahnsteigen liegen vier weitere im Untergrund — für S-Bahnen, die unter der Innenstadt weiterfahren.',
    pl: 'Frankfurt ma 24 perony naziemne i około 493 tysięcy pasażerów dziennie — drugie miejsce w kraju. Pod peronami naziemnymi leżą jeszcze cztery podziemne — dla pociągów miejskich jadących dalej pod centrum.',
  },
  'fact.38': {
    uk: 'Франкфуртський вокзал відкрито 1888 року; сьогодні через нього проходить 13 ліній ICE. Це головний пересадковий вузол країни: з нього можна виїхати в будь-який великий німецький місто без пересадок.',
    en: 'Frankfurt’s station opened in 1888; today 13 ICE lines pass through it. It is the country’s main interchange: you can reach any large German city from it without changing trains.',
    de: 'Der Frankfurter Hauptbahnhof wurde 1888 eröffnet; heute verkehren dort 13 ICE-Linien. Er ist der wichtigste Umsteigeknoten des Landes: Von hier erreicht man jede große deutsche Stadt ohne Umstieg.',
    pl: 'Dworzec we Frankfurcie otwarto w 1888 roku; dziś przechodzi przez niego 13 linii ICE. To główny węzeł przesiadkowy kraju: można stąd dojechać do każdego dużego niemieckiego miasta bez przesiadki.',
  },
  'fact.39': {
    uk: 'Кельн пропускає близько 1 200 потягів і 280 тисяч пасажирів щодня. Це один потяг щохвилини, і при цьому вокзал має лише одинадцять колій — щільність руху тут майже гранична.',
    en: 'Cologne handles about 1,200 trains and 280,000 passengers a day. That is a train a minute, and the station has only eleven tracks — traffic density here is close to the limit.',
    de: 'Köln wickelt täglich rund 1 200 Züge und 280 000 Reisende ab. Das ist ein Zug pro Minute, und der Bahnhof hat nur elf Gleise — die Verkehrsdichte liegt fast am Limit.',
    pl: 'Kolonia obsługuje około 1 200 pociągów i 280 tysięcy pasażerów dziennie. To jeden pociąg na minutę, a dworzec ma tylko jedenaście torów — gęstość ruchu jest tu niemal graniczna.',
  },
  'fact.40': {
    uk: 'Кельнський вокзал відкрили 5 грудня 1859 року просто біля собору — на місці колишнього ботанічного саду. Собор через це десятиліттями стоїть у диму й гуркоті — містяни сперечались про це ще у ХІХ столітті.',
    en: 'Cologne’s station opened on 5 December 1859 right beside the cathedral — on the site of a former botanical garden. The cathedral has therefore stood in smoke and rattle for decades — locals argued about it back in the 19th century.',
    de: 'Der Kölner Hauptbahnhof wurde am 5. Dezember 1859 direkt neben dem Dom eröffnet — auf dem Gelände eines früheren Botanischen Gartens. Der Dom steht deshalb seit Jahrzehnten in Rauch und Lärm — darüber stritt man schon im 19. Jahrhundert.',
    pl: 'Dworzec w Kolonii otwarto 5 grudnia 1859 roku tuż obok katedry — na terenie dawnego ogrodu botanicznego. Katedra stoi przez to od dziesięcioleci w dymie i hałasie — mieszkańcy spierali się o to już w XIX wieku.',
  },
  'fact.41': {
    uk: 'Гогенцоллернівський міст, що веде від кельнського вокзалу через Рейн, несе шість колій. Поруч із коліями йдуть пішохідна й велосипедна доріжки, а поручні міста давно завішані замками закоханих.',
    en: 'The Hohenzollern Bridge leading from Cologne’s station across the Rhine carries six tracks. A footway and a cycle path run beside the tracks, and the railings have long been hung with love locks.',
    de: 'Die Hohenzollernbrücke, die vom Kölner Hauptbahnhof über den Rhein führt, trägt sechs Gleise. Neben den Gleisen verlaufen ein Fuß- und ein Radweg, und die Geländer hängen längst voller Liebesschlösser.',
    pl: 'Most Hohenzollernów, prowadzący od dworca w Kolonii przez Ren, niesie sześć torów. Obok torów biegną chodnik i ścieżka rowerowa, a barierki od dawna obwieszone są kłódkami zakochanych.',
  },
  'fact.42': {
    uk: 'Берлінський головний вокзал відкрили аж у 2006 році — 430 метрів завдовжки і п’ять рівнів. До нього далекі потяги через Берлін не проходили наскрізь — місто розділяла стіна, і вокзали були тупиковими.',
    en: 'Berlin’s central station opened only in 2006 — 430 metres long and five levels deep. Before it, long-distance trains did not run through Berlin — the wall split the city and the stations were dead ends.',
    de: 'Der Berliner Hauptbahnhof wurde erst 2006 eröffnet — 430 Meter lang und fünf Ebenen hoch. Zuvor fuhren Fernzüge nicht durch Berlin — die Mauer teilte die Stadt, die Bahnhöfe waren Kopfbahnhöfe.',
    pl: 'Dworzec główny w Berlinie otwarto dopiero w 2006 roku — 430 metrów długości i pięć poziomów. Wcześniej pociągi dalekobieżne nie przejeżdżały przez Berlin — mur dzielił miasto, a dworce były czołowe.',
  },
  'fact.43': {
    uk: 'Через Берлін-Гауптбангоф щодня проходить близько 1 800 потягів і 300 тисяч пасажирів. Верхній рівень іде зі сходу на захід, нижній — з півночі на південь: вокзал працює як перехрестя на двох поверхах.',
    en: 'About 1,800 trains and 300,000 passengers pass through Berlin Hauptbahnhof every day. The upper level runs east-west, the lower north-south: the station works as a crossroads on two floors.',
    de: 'Täglich passieren rund 1 800 Züge und 300 000 Reisende den Berliner Hauptbahnhof. Die obere Ebene verläuft ost-west, die untere nord-süd: Der Bahnhof ist eine Kreuzung auf zwei Etagen.',
    pl: 'Przez Berlin Hauptbahnhof przechodzi dziennie około 1 800 pociągów i 300 tysięcy pasażerów. Górny poziom biegnie ze wschodu na zachód, dolny z północy na południe: dworzec działa jak skrzyżowanie na dwóch piętrach.',
  },
  'fact.44': {
    uk: 'Скляний дах берлінського вокзалу — приблизно 85 на 120 метрів, із вбудованими сонячними панелями. Панелі дають близько двох відсотків енергії будівлі — символічно, але дах однаково мав бути прозорим.',
    en: 'The glass roof of Berlin’s station is roughly 85 by 120 metres, with built-in solar panels. The panels supply about two per cent of the building’s power — symbolic, but the roof had to be transparent anyway.',
    de: 'Das Glasdach des Berliner Hauptbahnhofs misst etwa 85 mal 120 Meter und trägt integrierte Solarmodule. Die Module liefern etwa zwei Prozent des Gebäudestroms — symbolisch, aber das Dach sollte ohnehin transparent sein.',
    pl: 'Szklany dach berlińskiego dworca ma około 85 na 120 metrów, z wbudowanymi panelami słonecznymi. Panele dają około dwóch procent energii budynku — symbolicznie, ale dach i tak miał być przezroczysty.',
  },
  'fact.45': {
    uk: 'Дамба Гінденбурга веде на острів Зильт із 1927 року: 11 кілометрів колії й жодної автомобільної смуги. Автомобілі на острів потрапляють лише на платформах потяга — інакше туди просто не доїхати.',
    en: 'The Hindenburgdamm has led to the island of Sylt since 1927: eleven kilometres of track and not a single road lane. Cars reach the island only on train flatcars — there is no other way to get there.',
    de: 'Der Hindenburgdamm führt seit 1927 zur Insel Sylt: elf Kilometer Gleis und keine einzige Fahrspur. Autos kommen nur auf Bahnwagen auf die Insel — anders geht es nicht.',
    pl: 'Grobla Hindenburga prowadzi na wyspę Sylt od 1927 roku: jedenaście kilometrów toru i ani jednego pasa dla aut. Samochody dostają się na wyspę tylko na platformach pociągu — inaczej się tam nie dojedzie.',
  },
  'fact.46': {
    uk: 'Дамбою на Зильт щодня проходить понад сотня потягів, а за рік вони перевозять понад 450 тисяч автомобілів. У шторм дамбу заливає, і тоді острів на кілька годин лишається без сполучення з материком.',
    en: 'More than a hundred trains cross the Sylt causeway daily, carrying over 450,000 cars a year. In a storm the causeway floods, and the island is cut off from the mainland for a few hours.',
    de: 'Täglich überqueren über hundert Züge den Sylter Damm; im Jahr befördern sie mehr als 450 000 Autos. Bei Sturm wird der Damm überspült, und die Insel ist für Stunden vom Festland abgeschnitten.',
    pl: 'Przez groblę na Sylt przejeżdża dziennie ponad sto pociągów, a rocznie przewożą ponad 450 tysięcy aut. Podczas sztormu grobla jest zalewana i wyspa na kilka godzin traci połączenie z lądem.',
  },
  'fact.47': {
    uk: 'Найвища станція країни — Цугшпітцплатт на 2 650 метрах. Лінія від Гарміш-Партенкірхена завдовжки 19 кілометрів. Останні кілометри лінія йде в тунелі всередині гори, тож пасажир піднімається на дві тисячі метрів, не бачачи неба.',
    en: 'The country’s highest station is Zugspitzplatt at 2,650 metres. The line from Garmisch-Partenkirchen is 19 kilometres long. The last kilometres run in a tunnel inside the mountain, so passengers climb two thousand metres without seeing the sky.',
    de: 'Die höchste Station des Landes ist das Zugspitzplatt auf 2 650 Metern. Die Strecke ab Garmisch-Partenkirchen ist 19 Kilometer lang. Die letzten Kilometer verlaufen im Tunnel im Berginneren — man steigt zweitausend Meter auf, ohne den Himmel zu sehen.',
    pl: 'Najwyższa stacja kraju to Zugspitzplatt na 2 650 metrach. Linia z Garmisch-Partenkirchen ma 19 kilometrów. Ostatnie kilometry linia biegnie w tunelu wewnątrz góry, więc pasażer wspina się dwa tysiące metrów, nie widząc nieba.',
  },
  'fact.48': {
    uk: 'Баварська Цугшпітцбан має метрову колію і зубчасту систему Ріггенбаха; перепад висот 1 945 метрів — найбільший в Європі. Під час будівництва тунелю робітники наткнулись на вічну кригу, і склепіння довелось окремо укріплювати.',
    en: 'The Bavarian Zugspitze Railway runs on metre gauge with a Riggenbach rack; its 1,945-metre climb is the greatest in Europe. While digging the tunnel the crews hit permanent ice, and the vault had to be reinforced separately.',
    de: 'Die Bayerische Zugspitzbahn fährt auf Meterspur mit Riggenbach-Zahnstange; ihr Höhenunterschied von 1 945 Metern ist der größte Europas. Beim Tunnelbau stießen die Arbeiter auf ewiges Eis, das Gewölbe musste eigens gesichert werden.',
    pl: 'Bawarska Zugspitzbahn ma tor metrowy i zębatkę Riggenbacha; różnica wysokości 1 945 metrów jest największa w Europie. Podczas drążenia tunelu robotnicy natrafili na wieczny lód i sklepienie trzeba było osobno wzmocnić.',
  },
  'fact.49': {
    uk: 'У Гарці досі працює метрова мережа завдовжки близько 140 кілометрів, і значну частину потягів там тягнуть паровози. Головний напрямок — Броккен, найвища гора півночі Німеччини, і потяг туди йде дві години з димом і свистками.',
    en: 'The Harz still runs a metre-gauge network of about 140 kilometres, and steam hauls a large share of its trains. The main destination is the Brocken, the highest peak in northern Germany, a two-hour ride of smoke and whistles.',
    de: 'Im Harz fährt bis heute ein Meterspurnetz von rund 140 Kilometern, und einen großen Teil der Züge ziehen Dampfloks. Hauptziel ist der Brocken, der höchste Berg Norddeutschlands — zwei Stunden Fahrt mit Rauch und Pfiffen.',
    pl: 'W Harzu wciąż działa sieć metrowa o długości około 140 kilometrów, a znaczną część pociągów ciągną parowozy. Głównym kierunkiem jest Brocken, najwyższa góra północnych Niemiec — dwie godziny jazdy w dymie i gwizdach.',
  },
  'fact.50': {
    uk: 'Рендсбурзький високий міст 1913 року: 2 486 метрів, 42 метри просвіту над Кільським каналом і петля на 360 градусів, щоб спуститись до вокзалу. Петля була дешевшою за естакаду через усе місто: колія намотує коло радіусом у сотні метрів просто над дахами.',
    en: 'The Rendsburg High Bridge of 1913: 2,486 metres long, 42 metres of clearance over the Kiel Canal and a 360-degree loop to come back down to the station. The loop was cheaper than a viaduct across the whole town: the track winds a circle hundreds of metres wide right over the roofs.',
    de: 'Die Rendsburger Hochbrücke von 1913: 2 486 Meter lang, 42 Meter Durchfahrtshöhe über dem Nord-Ostsee-Kanal und eine 360-Grad-Schleife hinunter zum Bahnhof. Die Schleife war billiger als eine Rampe quer durch die Stadt: Das Gleis dreht einen Kreis von hunderten Metern über den Dächern.',
    pl: 'Most wysoki w Rendsburgu z 1913 roku: 2 486 metrów długości, 42 metry prześwitu nad Kanałem Kilońskim i pętla o 360 stopni, by zjechać do dworca. Pętla była tańsza niż estakada przez całe miasto: tor zatacza koło o promieniu setek metrów tuż nad dachami.',
  },
  'fact.51': {
    uk: 'Під рендсбурзьким мостом висить пором-гондола: 125 метрів через канал за 90 секунд, кожні чверть години. Це один із небагатьох діючих транспортних мостів у світі — гондола висить на тросах під самим прогоном.',
    en: 'A gondola ferry hangs beneath the Rendsburg bridge: 125 metres across the canal in 90 seconds, every quarter of an hour. It is one of the few working transporter bridges in the world — the gondola hangs on cables under the span.',
    de: 'Unter der Rendsburger Brücke hängt eine Schwebefähre: 125 Meter über den Kanal in 90 Sekunden, alle Viertelstunde. Sie ist eine der wenigen funktionierenden Schwebefähren der Welt — die Gondel hängt an Seilen unter dem Träger.',
    pl: 'Pod mostem w Rendsburgu wisi prom gondolowy: 125 metrów przez kanał w 90 sekund, co kwadrans. To jeden z niewielu działających mostów transportowych na świecie — gondola wisi na linach pod przęsłem.',
  },
  'fact.52': {
    uk: 'Вупперталь їздить підвісною дорогою з 1901 року — 13,3 кілометра над річкою й вулицями, близько 82 тисяч пасажирів щодня. Вагони їдуть під рейкою, а не по ній, і вся дорога тримається на металевих опорах прямо в руслі річки.',
    en: 'Wuppertal has run a suspension railway since 1901 — 13.3 kilometres above the river and the streets, about 82,000 passengers a day. The cars hang beneath the rail rather than riding on it, and the whole line stands on steel supports in the river bed.',
    de: 'Wuppertal fährt seit 1901 mit der Schwebebahn — 13,3 Kilometer über Fluss und Straßen, rund 82 000 Fahrgäste täglich. Die Wagen hängen unter der Schiene, statt darauf zu fahren, und die ganze Strecke steht auf Stahlstützen im Flussbett.',
    pl: 'Wuppertal jeździ koleją podwieszaną od 1901 roku — 13,3 kilometra nad rzeką i ulicami, około 82 tysięcy pasażerów dziennie. Wagony jadą pod szyną, a nie po niej, a cała trasa stoi na stalowych podporach w korycie rzeki.',
  },
  'fact.53': {
    uk: 'У 1950-му з вагона вупперталької підвісної дороги в річку впало слоненя Туффі — цирковий трюк пішов не за планом. Слоненя вижило. Туффі відбулась подряпинами, а от репортери, які писали про подію, отримали штраф разом із директором цирку.',
    en: 'In 1950 a baby elephant named Tuffi fell from a Wuppertal suspension railway car into the river — a circus stunt that went sideways. She survived. Tuffi escaped with scratches, while the reporters covering it were fined along with the circus director.',
    de: '1950 fiel das Elefantenbaby Tuffi aus einem Wagen der Wuppertaler Schwebebahn in den Fluss — ein Zirkus-Werbegag lief schief. Es überlebte. Tuffi kam mit Kratzern davon, die berichtenden Reporter wurden zusammen mit dem Zirkusdirektor bestraft.',
    pl: 'W 1950 roku z wagonu wuppertalskiej kolei podwieszanej wpadła do rzeki słonica Tuffi — cyrkowy trik poszedł nie tak. Przeżyła. Tuffi wyszła z zadrapaniami, a relacjonujący reporterzy dostali karę razem z dyrektorem cyrku.',
  },

  // --- джерела даних ---
  'sources.open': {
    uk: 'Джерела',
    en: 'Sources',
    de: 'Quellen',
    pl: 'Źródła',
  },
  'sources.title': {
    uk: 'Звідки тут дані',
    en: 'Where the data comes from',
    de: 'Woher die Daten stammen',
    pl: 'Skąd pochodzą dane',
  },
  'sources.lead': {
    uk: 'Сторінка не має власних даних: розклад, геометрія країни й факти взяті з відкритих джерел. Ось усі вони.',
    en: 'This page has no data of its own: the timetable, the country geometry and the facts all come from open sources. Here they all are.',
    de: 'Diese Seite hat keine eigenen Daten: Fahrplan, Landesgeometrie und Fakten stammen aus offenen Quellen. Hier sind sie alle.',
    pl: 'Ta strona nie ma własnych danych: rozkład, geometria kraju i ciekawostki pochodzą z otwartych źródeł. Oto wszystkie.',
  },
  'sources.facts': {
    uk: 'Факти — статті англомовної Вікіпедії',
    en: 'Facts — articles from the English Wikipedia',
    de: 'Fakten — Artikel der englischen Wikipedia',
    pl: 'Ciekawostki — artykuły angielskiej Wikipedii',
  },
  'sources.photos': {
    uk: 'Кадрів із «Дитинства Шелдона» у відкритій збірці немає: права на серіал належать студії. Вікна працюють без них.',
    en: 'The Young Sheldon frames are not part of the public build: the show belongs to its studio. The windows work without them.',
    de: 'Die Bilder aus „Young Sheldon“ sind nicht Teil des öffentlichen Builds: Die Serie gehört ihrem Studio. Die Fenster funktionieren auch ohne sie.',
    pl: 'Kadrów z „Młodego Sheldona” nie ma w publicznej wersji: prawa do serialu należą do studia. Okna działają bez nich.',
  },
  'sources.gtfs': {
    uk: 'Розклад: агрегує національний DELFI. Зібрано з rv_free — лише регіональні потяги, без ICE.',
    en: 'The timetable: aggregates the national DELFI feed. Built from rv_free — regional trains only, no ICE.',
    de: 'Der Fahrplan: aggregiert den nationalen DELFI-Datensatz. Gebaut aus rv_free — nur Regionalzüge, kein ICE.',
    pl: 'Rozkład: agreguje krajowy DELFI. Zbudowany z rv_free — tylko pociągi regionalne, bez ICE.',
  },
  'sources.states': {
    uk: 'Межі земель для власної карти; походять із VG2500 Федерального відомства картографії.',
    en: 'State borders for our own base map; derived from VG2500 by the Federal Agency for Cartography.',
    de: 'Ländergrenzen für die eigene Grundkarte; abgeleitet aus VG2500 des Bundesamts für Kartographie.',
    pl: 'Granice krajów związkowych dla własnej mapy; pochodzą z VG2500 Federalnego Urzędu Kartografii.',
  },
  'sources.osrm': {
    uk: 'Пішохідний маршрут Вайнгайм — Гейдельберг прокладено один раз і збережено в коді.',
    en: 'The Weinheim — Heidelberg walking route was computed once and stored in the code.',
    de: 'Die Fußstrecke Weinheim — Heidelberg wurde einmal berechnet und im Code gespeichert.',
    pl: 'Trasę pieszą Weinheim — Heidelberg wyznaczono raz i zapisano w kodzie.',
  },
  'sources.carto': {
    uk: 'Друга підкладка на вибір — коли потрібен контекст: дороги, міста, сусідні країни.',
    en: 'The alternative base map, for when you need context: roads, towns, neighbouring countries.',
    de: 'Die zweite Grundkarte zur Auswahl — wenn Kontext nötig ist: Straßen, Städte, Nachbarländer.',
    pl: 'Druga podkładka do wyboru — gdy potrzebny jest kontekst: drogi, miasta, sąsiednie kraje.',
  },
  'sources.maplibre': {
    uk: 'Рушій карти; звідти ж беруться шрифти-гліфи для підписів.',
    en: 'The map engine; its font glyphs are used for the labels too.',
    de: 'Die Kartenbibliothek; von dort stammen auch die Glyphen für die Beschriftungen.',
    pl: 'Silnik mapy; stamtąd pochodzą też glify czcionek do podpisów.',
  },
  'sources.fonts': {
    uk: 'Шрифти інтерфейсу й моноширинного табло.',
    en: 'Typefaces for the interface and the mechanical board.',
    de: 'Schriften für die Oberfläche und die Fallblattanzeige.',
    pl: 'Kroje pisma interfejsu i mechanicznej tablicy.',
  },
};
